### ISSUE TITLE
Données de l'utilisateur transmises à un tier : non-respect de la politique de confidentialité et des promesses faites aux élèves

### ISSUE THREAD

**Issue by Vilerio** [PapillonApp/papillon-v7#100]
Contenu du fichier `src/utils/external/generate-pass.ts` :

```
const URL = "https://papillon-pass-api.vercel.app/api/generate-pass";

interface GeneratePassData {
  name: string;
  classe: string;
  service: string;
  data: string;
  type: string;
  encoding: string;
}

export const generatePass = async (data: GeneratePassData) => {
  const response = await fetch(`${URL}?name=${data.name}&classe=${data.classe}&service=${data.service}&type=${data.type}&data=${data.data}&encoding=${data.encoding}`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });

  return response;
};

```

On voit ici clairement l'envoi de données personnelles de l'utilisateur aux serveurs derrière le DNS "papillon-pass-api.vercel.app". Cet enregistrement DNS semble pointer vers une adresse ip appartenant à Amazon.
Par conséquent, nous pouvons en déduire que des données personnelles des élèves utilisant Papillon peuvent être transmises aux serveurs d'Amazon, possiblement hors de l'union européenne, hors de la legislation du RGPD. "Vercel Inc." fournissant un service "Function as a service", "l'équipe Papillon" n'a pas le contrôle sur les données transmises via cet enregistrement DNS.
En outre, nous n'avons pas connaissance du code source de l'api disponible à l'adresse "https://papillon-pass-api.vercel.app/api/generate-pass", ce qui est un danger de plus pour l'utilisateur, qui n'a pas connaissance de la façon dont sont traitées, stockées et utilisées ses données par cette api. De plus, aucun fichier de mentions légales ou autre ne nous permet de connaitre le responsable de ce site, ce dernier n'étant pas conforme à la Loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique.

Papillon s'affirme comme "Sécurisée et respectue(use) de votre vie privée", et que "Vos données sont sur votre appareil et ne sont jamais partagées avec des tiers".
Il est également indiqué sur ce site que "Papillon est un logiciel libre et open-source \ Créé par des élèves pour des élèves, modifiable par n'importe qui" ; n'importe qui ne peut pas utiliser et modifier pleinement Papillon soit avoir connaissance du code présent derrière cette api.

Ce morceau de code rend ces informations fallacieuses. Ainsi, je demande la suppression de l'accès à cette api, qui peut être remplacée par un autre fichier `utils`, qui permettra aux données de l'élèves de rester sur son smartphone en obtenant un résultat identique, ainsi que la mise à disposition du code source de cette api sous licence AGPLv3. Ou à défaut la suppression des mentions de l'aspect "sécurisé, confidentiel et open source" de Papillon.

PS : je ne vois vraiment pas l'utilité d'un tel appel à une api, pourquoi ne pas faire ça en local ? Et niveau confidentialité, ça craint sérieux, vous avez abusé... Voilà l’intérêt de review ;)

**Comment by tryon-dev** [comment]
Hey, actuellement cette api n'est pas utilisé dans notre application, elle n'a été seulement pendant le développement pour expérimenter les cartes Apple wallet, cette api actuellement n'est pas en service et le sera quand les cantine arriverons

Mais oui bien sûr nous pouvons retirer il n'y a pas de souci problème

**Comment by tryon-dev** [comment]
+ Apple nous oblige à faire de cette méthode à cause de leur façon de signer les passes

**Comment by Vilerio** [comment]
> Hey, actuellement cette api n'est pas utilisé dans notre application, elle n'a été seulement pendant le développement pour expérimenter les cartes Apple wallet, cette api actuellement n'est pas en service et le sera quand les cantine arriverons
> 
> Mais oui bien sûr nous pouvons retirer il n'y a pas de souci problème

J'ai vu qu'elle n'est pas utilisée, mais si ce code est ici, c'est, comme tu le dis, qu'elle sera un jour en service. Le problème se présentera donc à ce moment là.
Si tu as plus de détails sur ce qui vous oblige à faire ça, je suis preneur, afin que nous trouvions ensemble un moyen de garder la fonctionnalité sans pour autant compromettre la sécurité des élèves.

**Comment by tryon-dev** [comment]
Nous allons trouver une solution et même l'hébergement de l'api ne sera plus chez Vercel mais sur des serveurs français + le code sera bientôt disponible sur note GitHub 
Je te donne plus d'info dès que je me remet sur cette fonctionnalité

**Comment by TinAD17tin** [comment]
J’pense faut l’enlever comme ça AUCUN problème avec PRONOTE

**Comment by Vilerio** [comment]
> Nous allons trouver une solution et même l'hébergement de l'api ne sera plus chez Vercel mais sur des serveurs français + le code sera bientôt disponible sur note GitHub Je te donne plus d'info dès que je me remet sur cette fonctionnalité

Ok nickel, quand la feature sera implémentée proprement mets le code et les refs en question dans l'issue stp et tu pourras la fermer à ce moment là ;)

**Comment by Vilerio** [comment]
> > Nous allons trouver une solution et même l'hébergement de l'api ne sera plus chez Vercel mais sur des serveurs français + le code sera bientôt disponible sur note GitHub Je te donne plus d'info dès que je me remet sur cette fonctionnalité
> 
> Ok nickel, quand la feature sera implémentée proprement mets le code et les refs en question dans l'issue stp et tu pourras la fermer à ce moment là ;)

C'est surtout vis-à-vis de l'utilisateur le problème, il faut oeuvrer pour sa sécurité avant tout pour lui, pas pour une entreprise..

**Comment by Gabriel29306** [comment]
> J’pense faut l’enlever comme ça AUCUN problème avec PRONOTE

Le code sera open-source (à pars les clés pour signer les pass, logique). Donc en théorie 0 problème car il y aura un suivi de A à Z de l'information de de sa manipulation.

**Comment by Vilerio** [comment]
> > J’pense faut l’enlever comme ça AUCUN problème avec PRONOTE
> 
> Le code sera open-source (à pars les clés pour signer les pass, logique). Donc en théorie 0 problème car il y aura un suivi de A à Z de l'information de de sa manipulation.

Si tu parles de rester sur ce système d'api, non, l'information sera toujours transmise à Amazon par l'intermédiaire de Vercel. 
En outre, les élèves n'ont pas la garantie que c'est bien la même version du code et sur le repo et sur le Vercel.

**Comment by Gabriel29306** [comment]
On peut hoster l'api sur GitHub pages

**Comment by Vilerio** [comment]
Ah bah si tu préfères Microsoft à Amazon why not xD

**Comment by Gabriel29306** [comment]
Tu veux faire comment sinon ? On peut pas laisser des clés de signatures dans la nature.

**Comment by Vilerio** [comment]
Je n'ai pas encore lu la doc complète d'Apple à ce sujet, mais je reviendrai vers toi quand je l'aurais fait et discuté d'une solution avec les autres.

**Comment by maelgangloff** [comment]
Je ne sais pas à quoi sert ce Pass (je crois que l'information n'a pas été donnée dans cette issue non plus).
Pour éviter de potentiels soucis, je vous conseille de faire en sorte qu'**aucune donnée personnelle** d'élève ne transite hors de Papillon hormis des données anonymisées.

**Comment by oriionn** [comment]
> Hey, actuellement cette api n'est pas utilisé dans notre application, elle n'a été seulement pendant le développement pour expérimenter les cartes Apple wallet, cette api actuellement n'est pas en service et le sera quand les cantine arriverons
> 
> Mais oui bien sûr nous pouvons retirer il n'y a pas de souci problème

L'utilité de cette api est énoncé ici ;)

**Comment by maelgangloff** [comment]
Si c'est juste pour les cartes de cantine, veillez à ce qu'aucune donnée personnelle d'élève ne transite en dehors de l'application Papillon.
Dans le cas contraire, implémentez la carte directement dans un onglet de l'app ou trouvez une solution alternative.
La sécurité des données des utilisateurs de Papillon doit être **irréprochable** et vous devez pouvoir démontrer que ces données ne peuvent pas fuiter.

**Comment by tom-theret** [comment]
Il est tout-à-fait possible d’utiliser un serveur Web sans transmettre des données personnelles en clair.

**Comment by tryon-dev** [comment]
J'ai retiré les bouts de code mentionné, sinon je close l'issue j'en réouvrirais une autre quand je me remettrais dessus 
merci encore @Vilerio d'avoir report ceci, en effet ceci est un bout de code oublié et uniquement afin de développer les Pass IOS
qui ressemble a ceci : 
![image](https://github.com/user-attachments/assets/d5c5a683-7f62-4dac-a416-4f7d513bf781)

Sinon papillon n'utilisera plus cette api pour générer des passes et lorsque que nous introduirons cette feature elles sera documenté, et surtout disponible en source ouverte
