### ISSUE TITLE
[Question]: Développement d'extensions

### ISSUE THREAD

**Issue by Aymano200** [PapillonApp/papillon-v7#106]
### Description de la fonctionnalité

Bonjour, j’ai une question, comment pourrait-je développer un plugin papillon ? Avec quel language de programmation ? Qu’est-ce que ça me permettrait de faire ? Est-ce qu’il sera possible de créer son propre thème en modifiant la couleur des boutons de l’arrière-plan etc ?

Sinon super projet j’aime beaucoup ça s’est amélioré depuis 1 an.

**Comment by Gabriel29306** [comment]
Les extensions seront développées en HTML/CSS/JS.
La documentation n'est pas encore publique (je ne sais même pas si elle est écrite). Elle le sera quand la fonctionnalité sera implémentée.

**Comment by godetremy** [comment]
> ### Description de la fonctionnalité
> Bonjour, j’ai une question, comment pourrait-je développer un plugin papillon ? Avec quel language de programmation ? Qu’est-ce que ça me permettrait de faire ? Est-ce qu’il sera possible de créer son propre thème en modifiant la couleur des boutons de l’arrière-plan etc ?
> 
> Sinon super projet j’aime beaucoup ça s’est amélioré depuis 1 an.
> 
> ### Contexte supplémentaire
> _No response_

Oups, pas vu désolé !!! Je vais répondre à vos question ici du coup :

### Avec quel language de programmation ?
Les extensions seront développer en HTML / CSS / JS
### Qu’est-ce que ça me permettrait de faire ?
Tu as beaucoup de possibilité ! Crée des pages, pouvoir utiliser les donnée scolaire de l'utilisateur, executer du JS durant l'utilisation de l'app, etc... 
### Est-ce qu’il sera possible de créer son propre thème en modifiant la couleur des boutons de l’arrière-plan etc ?
En revanche les interfaces sont seulement dans des endroit définis, donc tu ne peux modifier le style de Papillon avec une extension !
### Sinon super projet j’aime beaucoup ça s’est amélioré depuis 1 an.
🫶

N'hésite pas à me ping sur discord si je répond pas ! 👀
