### ISSUE TITLE
[Enhancement]: NaN moyenne si 0 notes

### ISSUE THREAD

**Issue by Cleboost** [PapillonApp/papillon-v7#129]
### Description du problème

Quand nous n'avons pas de note, le widget sur la home page affiche NaN/20
![image](https://github.com/user-attachments/assets/d05ce829-a5d1-4c80-8de5-935b97949f37)

### Description de l'amélioration

Peut être ne juste pas afficher le widget si nous n'avons pas de note

### Contexte supplémentaire

Je n'ai aucune note

**Comment by Rexxt** [comment]
ça devrait être un ez fix

**Comment by Rexxt** [comment]
@ecnivtwelve ⬆️

**Comment by Slysoks** [comment]
En sois on ne reste qu'une ou deux semaines sans notes, ce n'est donc par conséquent pas grave si la moyenne est affichée

**Comment by TinAD17tin** [comment]
J’avoue qu’en vrai ça serait encore plus magic 🪄

**Comment by Cleboost** [comment]
> En sois on ne reste qu'une ou deux semaines sans notes, ce n'est donc par conséquent pas grave si la moyenne est affichée

Oui ca n'a rien de grave ni urgent mais c'est pour tendre vers la perfection ⭐

**Comment by Slysoks** [comment]
En tout cas je l'ai mis dans ma PR si jamais...
