### ISSUE TITLE
[Feature]: Version Web

### ISSUE THREAD

**Issue by Aymano200** [PapillonApp/papillon-v7#130]
### Description de la fonctionnalité

Une version web pour papillon serait super

**Comment by Slysoks** [comment]
Il faudrait refaire un côté responsive parfois "relou", mais autrement il n'y aurait rien d'autre à faire.

**Comment by vexcited** [comment]
Une version web ? Tu veux dire un site Internet ?

Si oui, ce n'est malheureusement pas possible à cause de la RGPD et des règles strictes qu'impose Index-Education.
On s'est déjà fait tapé sur les doigts par le passé pour ça, alors on va éviter de refaire la même erreur 😉

**Comment by NonozgYtb** [comment]
J'ajoute que Skolengo bloque également cela puisqu'on à besoin d'utiliser le deeplinking, ce qui ne peut pas se faire sur le web.

**Comment by Rexxt** [comment]
un port natif PC ça peut s'envisager par contre je pense

**Comment by vexcited** [comment]
> un port natif PC ça peut s'envisager par contre je pense

Oui ça c'est grave possible cependant (mais pas la priorité pour le moment...)
