### ISSUE TITLE
[Feature]: Accès au contenu du cours

### ISSUE THREAD

**Issue by Aymano200** [PapillonApp/papillon-v7#132]
### Description de la fonctionnalité

Pouvoirs avoir accès au cahier de textes des cours ainsi qu’aux cours fichiers liés.

**Comment by TinAD17tin** [comment]
Donc aux contenus de cours si j’ai bien compris ?

**Comment by Slysoks** [comment]
Oui, je pense

**Comment by Aymano200** [comment]
> Donc aux contenus de cours si j’ai bien compris ?

Oui

**Comment by Clmnnt** [comment]
Je sais pas si vous pouvez aussi mettre les pièces jointes des devoirs ou non mais ça serait bien de l’avoir

**Comment by camarm-dev** [comment]
Fait pour ED par @imyanice dans #288, faudrait quelqu'un pour le faire avec PRONOTE. Je sais pas si pawnote intégre la fonctionnalité. Quelqu'un a des nouvelles / des informations là dessus ?

**Comment by Kgeek33** [comment]
je regarde et je te dis ça

**Comment by Kgeek33** [comment]
j'ai fait un peu de reecherche mais je trouve rien qui puisse permettre de récupérer le contenu des cours

**Comment by Gabriel29306** [comment]
Ça a été fait ?

**Comment by Clmnnt** [comment]
Je ne crois pas

**Comment by Orafilynie** [comment]
> Je ne crois pas

Ah bon ? De mémoire sur la V6 Pawnote ont pouvais le faire, même avec les PJs dans les contenu de cours...

**Comment by Kgeek33** [comment]
Non ça a pas été fait
@Orafilynie oui Papillon v6 le faisait mais il y a eu une maj de Pawnote qui ne supporte plus le contenu des cours (_sauf si j'ai pas assez approfondi les recherches, mais normalement, je me trompe pas_)
c'est comme les comptes parents. C'était supporté sur la V6 mais Pawnote le supporte plus depuis

**Comment by TinAD17tin** [comment]
Yes c’est bien ça, Mikkel l’avait dit sur Discord
