### ISSUE TITLE
[Enhancement]: Bandeau de couleur pour les modifs de cours

### ISSUE THREAD

**Issue by Vilerio** [PapillonApp/papillon-v7#136]
### Description du problème

La mention des cours annulés ou modifiés n'est pas assez visible.

### Description de l'amélioration

Rendre le bandeau rouge/autre couleur en fonction du besoin

**Comment by Slysoks** [comment]
Pouvez-vous faire une capture d'écran ?

**Comment by Vilerio** [comment]
> Pouvez-vous faire une capture d'écran ?

Je te laisse voir #139, j'y ai proposé une couleur avec une capture

**Comment by Slysoks** [comment]
Je pense donc que tu peux close cette issue

**Comment by Vilerio** [comment]
J'attends que la PR soit acceptée
