### ISSUE TITLE
[CANCELLED][Feature]: Icône d’app personnalisée

### ISSUE THREAD

**Issue by Clmnnt** [PapillonApp/papillon-v7#146]
### Description de la fonctionnalité

Donne le choix de mettre l’icône qu’on veut (en prenant une image dans la galerie).

**Comment by Gabriel29306** [comment]
Impossible. Quand on ajoute une icône à l'application, on est obligé de la déclarer avant de build l'application.

**Comment by Louis454545** [comment]
Je te conseille de close l'issue, sinon ta des applis pour faire des raccourcis avec d'autres icônes ou des modules si t'es root et sur iphone tu peux utiliser raccourcis !

**Comment by godetremy** [comment]
> Impossible. Quand on ajoute une icône à l'application, on est obligé de la déclarer avant de build l'application.
