### ISSUE TITLE
[Enhancement]: Modifier l'animation d'erreur lorsque le nombre d'onglet est supérieur à 5

### ISSUE THREAD

**Issue by godetremy** [PapillonApp/papillon-v7#166]
### Description du problème

L'animation semble confuse pour la plupart des utilisateurs (Romane n'as pas compris 😂)

### Description de l'amélioration

Modifier l'animation pour voir permettre à l'utilisateur de comprendre que la tabac est pleine

**Comment by Gabriel29306** [comment]
Je pense que l'animation est surtout trop rapide, elle ne laisse pas forcément le temps de voir le warning.

**Comment by Vilerio** [comment]
Fait dans #175 

https://github.com/user-attachments/assets/61f249c6-67e0-4272-983e-0e6ce69849ab

**Comment by Louis454545** [comment]
a close

**Comment by godetremy** [comment]
> a close

Non pour moi, c'est toujours pas assez clair !

**Comment by Rexxt** [comment]
je suis d'accord

**Comment by Kgeek33** [comment]
je vais corriger ça
