### ISSUE TITLE
[Enhancement]: Marquer tout les onglet désactivé comme disponible prochainement

### ISSUE THREAD

**Issue by godetremy** [PapillonApp/papillon-v7#168]
### Description du problème

Marquer tout les onglet désactivé comme disponible prochainement pour éviter les confusion

### Description de l'amélioration

Faire comme pour les extensions

**Comment by Vilerio** [comment]
Fait dans #175 
![IMG_5523](https://github.com/user-attachments/assets/c445d508-402b-48a7-a808-878982026882)
![IMG_5522](https://github.com/user-attachments/assets/cb0e7041-5c90-4355-b097-d8b9471f4b54)

**Comment by ecnivtwelve** [comment]
On peut close l'issue alors ! Merci Vilerio !
