### ISSUE TITLE
[Feature]: Crée un composant PapillonContextMenu

### ISSUE THREAD

**Issue by godetremy** [PapillonApp/papillon-v7#169]
### Description de la fonctionnalité

Crée un composant comme le sélecteur de compte qui pourrait s'intégrer dans les en-têtes, et dans les NativeList

**Comment by ecnivtwelve** [comment]
Normalement le composant peut être utilisé avec n'importe quel context menu à la place si je me trompe pas ? @tryon-dev c'était toi qui avait géré cela pour les comptes nan ?

**Comment by ecnivtwelve** [comment]
maintenant qu'il y a [`<PapillonPicker />`](https://github.com/PapillonApp/Papillon/blob/main/src/components/Global/PapillonPicker.tsx), est-ce toujours nécéssaire ? @godetremy
