### ISSUE TITLE
[Enhancement]: Régler le "double affichage" lors de l'actualisation de la page note

### ISSUE THREAD

**Issue by Gabriel29306** [PapillonApp/papillon-v7#172]
### Description du problème

Lors de l'actualisation de la page des notes, il y a une animation bizarre.

### Description de l'amélioration

Enlever cette animation bizarre.

### Contexte supplémentaire

https://github.com/user-attachments/assets/9a65b81b-0521-4328-a97a-37b555345237

**Comment by Cleboost** [comment]
@Gabriel29306 je crois que ca a été fix dans la pr
