### ISSUE TITLE
[Enhancement]: Réintégration du groupement des matières & surlignage

### ISSUE THREAD

**Issue by ecnivtwelve** [PapillonApp/papillon-v7#193]
### Description du problème

Il faut backport les dernières PR de @Louis-htmlcss dans les nouveaux devoirs

### Description de l'amélioration

- Ajout du groupement des matières de @Louis-htmlcss (https://github.com/PapillonApp/Papillon/pull/178)
- Ajout du surlignage de la recherche de @Louis-htmlcss (https://github.com/PapillonApp/Papillon/pull/192#discussion_r1760014657)

**Comment by Louis454545** [comment]
A close

**Comment by Kgeek33** [comment]
Je l'ai link sur ma pr :)
