### ISSUE TITLE
[Amélioration] : Dater les devoirs dans la page d’accueil

### ISSUE THREAD

**Issue by Clmnnt** [PapillonApp/papillon-v7#227]
### Description du problème

Dans l’app, les devoirs ne sont pas « datés » ( on ne sais pas pour quel jour on doit le faire)

### Description de l'amélioration

mettre « pour le …. » dans la liste des devoirs

### Contexte supplémentaire

Je possède la beta 7.2.0 (4) sur iOS 18.1

**Comment by Louis454545** [comment]
Bas on a la date où on doit le faire

**Comment by Clmnnt** [comment]
Dans la **_page d'accueil_**, sorry 
![image](https://github.com/user-attachments/assets/021872ed-9ad9-4785-96b6-228f9cb2125c)

**Comment by Kgeek33** [comment]
Je m'en occupe :)

**Comment by Louis-htmlcss** [comment]
Je ferais une pr pour fix ça
