### ISSUE TITLE
[Features] Messagerie PRONOTE 

### ISSUE THREAD

**Issue by Awakno** [PapillonApp/papillon-v7#230]
### Description de la fonctionnalité

Ajouter la messagerie PRONOTE à Papillon.

**Comment by Clmnnt** [comment]
C'est prévu et en développement !

**Comment by Awakno** [comment]
> C'est prévu et en développement !

Ah ok, je n’avais vu aucune issue ou PR dessus ^^

**Comment by Clmnnt** [comment]
C'est dans les branchs les principales features ![image](https://github.com/user-attachments/assets/7701b5f7-e2e3-4a5d-961b-74447493a12e)

**Comment by Awakno** [comment]
> C'est dans les branchs les principales features ![image](https://private-user-images.githubusercontent.com/159389431/371296732-7701b5f7-e2e3-4a5d-961b-74447493a12e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczODA4NzMsIm5iZiI6MTcyNzM4MDU3MywicGF0aCI6Ii8xNTkzODk0MzEvMzcxMjk2NzMyLTc3MDFiNWY3LWUyZTMtNGE1ZC05NjFiLTc0NDQ3NDkzYTEyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQxOTU2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGY1MWQ4Njk1ZGUyNzYzNzEzYmQ3MjMxOTFkNTM2ZmE4ZWFhYTJiMDdkNjIwNTQ1NTFhYmMxOGMxYTE4YTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7tpWaWrR_JUaEhTui9AxhCqVXyWA28GvdoCOXXjEoUI)

Ah ba my bad je suis aveugle

**Comment by Louis454545** [comment]
Tu peux close l'issue

**Comment by Clmnnt** [comment]
T'inquiètes c pas grave
