### ISSUE TITLE
[Feature]: deepsoruce

### ISSUE THREAD

**Issue by Louis454545** [PapillonApp/papillon-v7#237]
### Description de la fonctionnalité

ajouetr deepsource

**Comment by Gabriel29306** [comment]
... ?

**Comment by Louis454545** [comment]
> ... ?

Pour analyser les prs avant de les review

**Comment by Rexxt** [comment]
non

**Comment by Louis454545** [comment]
> non

si

**Comment by Louis454545** [comment]
> non

ya pas d'ia je crois donc bon

**Comment by Rexxt** [comment]
> > non
> 
> ya pas d'ia je crois donc bon

ça veut rien dire sale bâtard

**Comment by Kgeek33** [comment]
> Pour analyser les prs avant de les review

Analyser quoi ?

**Comment by Louis454545** [comment]
> > Pour analyser les prs avant de les review
> 
> Analyser quoi ?

Plein de choses,tu peux regarder sur leur site

**Comment by Kgeek33** [comment]
> > > Pour analyser les prs avant de les review
> > 
> > Analyser quoi ?
> 
> Plein de choses,tu peux regarder sur leur site

J'ai regardé et ça a l'air très intéressant, bonne idée

**Comment by Louis454545** [comment]
Bro 💀
