### ISSUE TITLE
[Feature]: Afficher les DS

### ISSUE THREAD

**Issue by GeoffreyGx** [PapillonApp/papillon-v7#240]
### Description de la fonctionnalité

Certains professeurs affichent les prochains DS sur Pronote indépendamment des devoirs. Il est donc impossible de les voir sur Papillon, puisque Papillon n'intègre pas cette fonctionnalité. Ce serait bien également que comme sur Pronote, cela s'affiche dans l'emploi du temps.

### Contexte supplémentaire

Affichage sur Pronote sur l'écran d'accueil
![image](https://github.com/user-attachments/assets/358bfe1a-73e4-4a07-864c-6feb28326873)

Affichage dans l'emploi du temps :
![image](https://github.com/user-attachments/assets/617ee8d7-07a6-4a96-8c96-cd733ab13dff)

**Comment by Gabriel29306** [comment]
@Vexcited c'est implémenté dans Pawnote ?

**Comment by vexcited** [comment]
L'affichage sur l'écran d'accueil n'est pas implémenté dans Pawnote.

Cependant le statut dans l'emploi du temps est implémenté.
