### ISSUE TITLE
[Bug] Login

### ISSUE THREAD

**Issue by Awakno** [PapillonApp/papillon-v7#248]
Plate-forme : IOS
Outils: PRONOTE
Problème lors de la connexion avec Identifiant + mot de passe 

![image](https://github.com/user-attachments/assets/75374098-f69c-4b1b-be81-0fb388579801)

**Comment by Kgeek33** [comment]
C'est pask ton compte nécessite un code pin à la connexion, qui a récemment été intégré : #239
