### ISSUE TITLE
[Bug] on click sur un cours

### ISSUE THREAD

**Issue by Awakno** [PapillonApp/papillon-v7#249]
Platform: IOS

https://github.com/user-attachments/assets/b44ba847-8703-4bc8-84c5-1aa91823a948

**Comment by Kgeek33** [comment]
Quelle version utilises-tu de Papillon ?

**Comment by Awakno** [comment]
> Quelle version utilises-tu de Papillon ? 

La dernière, la 7.1

**Comment by Kgeek33** [comment]
Ce bug a été corrigé sur la version 7.2 (ou 7.2.1), qui a été publié ajd

**Comment by Bulgus** [comment]
Problème présent sous iOS 18, version 7.2.1 de l'app (Testflight)

Edit : Pas de soucis avec npx sur le dernier commit, j'imagine qu'un patch à eu lieu mais n'est pas déployé ?

**Comment by Kgeek33** [comment]
> Problème présent sous iOS 18, version 7.2.1 de l'app (Testflight)
> 
> Edit : Pas de soucis avec npx sur le dernier commit, j'imagine qu'un patch à eu lieu mais n'est pas déployé ?

Bizarre, ça été corrigé depuis longtemps (_je recherche le commit_). Et je ne rencontre pas ce problème sur Android
Si vous cliquez sur une note, est-ce ça plante ? Et si ça plante pas, est-ce que c'est marqué "Matière inconnue"?

**Comment by Bulgus** [comment]
> Bizarre, ça été corrigé depuis longtemps (_je recherche le commit_). Et je ne rencontre pas ce problème sur Android Si vous cliquez sur une note, est-ce ça plante ? Et si ça plante pas, est-ce que c'est marqué "Matière inconnue"?

Nan sur une note pas de problème... mais tout fonctionne avec un build du repo que je viens de faire...

**Comment by Kgeek33** [comment]
C'est sûrement ton commit de tout à l'heure qui a dû corriger ce problème 🤷

**Comment by Bulgus** [comment]
> C'est sûrement ton commit de tout à l'heure qui a dû corriger ce problème 🤷

Ça serait étrange j'ai touché qu'a l'affichage du statut du cours.. à moi que ça ai causé le crash que celui ci soit pas défini. Bref c'est patch dans la prochaine maj du coup :)
