### ISSUE TITLE
[Bug] Professeur absent

### ISSUE THREAD

**Issue by Awakno** [PapillonApp/papillon-v7#253]
iOS
Version appli: 7.2.1

![image](https://github.com/user-attachments/assets/85320fe6-7287-4a67-bfac-248410205ff7)

![image](https://github.com/user-attachments/assets/69a3be74-c4c4-4607-bbec-09fd33a74519)

**Comment by Kgeek33** [comment]
T'as scrolé vers le bas pour actualiser la page ?
Ps: _si ça affiche "canceled" pour un prof absent, ça a été corrigé ajd, après la publication de la nouvelle version_

**Comment by Awakno** [comment]
> T'as scrolé vers le bas pour actualiser la page ?
> Ps: _si ça affiche "canceled" pour un prof absent, ça a été corrigé ajd, après la publication de la nouvelle version_

Ah ok mais c'est chiant de devoir actualiser à chaque fois, faudrait le faire auto dès qu'on va sur l'emploi du temps non ?

**Comment by Kgeek33** [comment]
> > T'as scrolé vers le bas pour actualiser la page ?
> > Ps: _si ça affiche "canceled" pour un prof absent, ça a été corrigé ajd, après la publication de la nouvelle version_
> 
> Ah ok mais c'est chiant de devoir actualiser à chaque fois, faudrait le faire auto dès qu'on va sur l'emploi du temps non ?

Oui, effectivement et c'est tjrs le cas en version dev.
À la limite, renomme l'issue pour dire que l'actualisation automatique de l'emploi du temps ne fonctionne pas. Et qqun s'en occupera ;)

**Comment by Kgeek33** [comment]
Ou l'actualisation automatique n'est pas intégré, jspas
