### ISSUE TITLE
[Enhancement]: Style margin-top devoirs

### ISSUE THREAD

**Issue by Slysoks** [PapillonApp/papillon-v7#255]
### Description du problème

Ouverture des devoirs trop haute. Il faudrait un margin-top. Sur la capture on ne voit pas mais ça monte jusqu'en haut de l'écran, plus haut que l'heure !

![Screenshot_20241003_101753_Papillon](https://github.com/user-attachments/assets/c7534879-0510-4a92-a4d4-c9f088381015)

### Description de l'amélioration

Ajouter un margin-top 100px par ex au niveau du slide to top des devoirs.

### Contexte supplémentaire

Android 14
Samsung A52 5G
Papillon v7.2.0

**Comment by Gabriel29306** [comment]
Duplicata de la #233
