### ISSUE TITLE
[Enhancement]: Center subject's icon

### ISSUE THREAD

**Issue by Slysoks** [PapillonApp/papillon-v7#256]
### Description du problème

En faisant mon issue précédente ( #255 ), j'ai remarqué que les icônes des matières n'étaient pas centrées

![image](https://github.com/user-attachments/assets/bf4273a5-c264-4afb-852e-67e22203bf96)
![image](https://github.com/user-attachments/assets/5966208a-f7ff-4386-bf68-ec3aab514e20)

### Description de l'amélioration

Mettre l'icône dans une view flex, justify & align center

### Contexte supplémentaire

Android 14
Samsung A52 5G
Papillon v7.2.0

**Comment by Kgeek33** [comment]
Si tu veux corriger, tu peux t'aider de ceci : https://github.com/PapillonApp/Papillon/pull/202#issuecomment-2389558209

**Comment by yannouuuu** [comment]
#202

**Comment by LeGeek01** [comment]
How to center a div

**Comment by Slysoks** [comment]
How to center a div without flexbox 😱😱😱

**Comment by Kgeek33** [comment]
En préparation ! _Spoiler, voici le code que j'utilise pour l'instant_ (je changerai d'autres choses pour que ça soit plus lisible) : 

`<View style={{ backgroundColor: subjectData.color + "22", borderRadius: 100, height: 40, width: 40, justifyContent: "center", alignItems: "center" }}>
              <Text style={{ textAlign: "center", fontSize: 20, lineHeight: 23, width: 40, fontFamily: "medium", textAlignVertical: "center" }}>
                {subjectData.emoji}
              </Text>`

**Comment by Slysoks** [comment]
G déjà fix chez moi tkt
