### ISSUE TITLE
[Feature]: Actualités

### ISSUE THREAD

**Issue by Kgeek33** [PapillonApp/papillon-v7#275]
### Description du problème

Sur Pronote (jspas sur les autres services), sur certaines informations et sondages/actualités, il arrive que celui qui envoie une actualité demande à cocher "J'ai pris connaissance de cette information" (_voir capture_)
![Screenshot_2024-10-08-11-43-11-222_com IndexEducation Pronote](https://github.com/user-attachments/assets/ebbbf731-4530-4925-a7b1-37f92f1c3e13)

### Description de l'amélioration

Ça serait bien de l'intégrer à papillon, ou alors quand on marque comme lue l'actualité, que ça coche cette case

### Contexte supplémentaire

@Vexcited est-ce que Pawnote prend en charge cette fonctionnalité ?

**Comment by Gabriel29306** [comment]
Je répond pour Vex, oui.
https://github.com/LiterateInk/Pawnote/blob/js/examples%2Fnews%2Facknowledge-information.ts

**Comment by Kgeek33** [comment]
***Aperçu du code que j'ai tenté***
ok, alors voici ce que j'ai fait, mais marche pas lors de la sauvegarde des modifs : (_acknowledged est la variable qui contient si l'utilisateur a coché ou non la case_)

`message.acknowledged = true;
                    message.ref.acknowledged = true;
                    message.ref.acknowledgedDate = new Date().toISOString();
setNewsRead(account, message, true);`

**Comment by Gabriel29306** [comment]
Ah non, il faut utiliser: 

```ts
pronote.newsInformationAcknowledge(session, item);
```

**Comment by vexcited** [comment]
C'est ça, voir l'exemple : https://github.com/LiterateInk/Pawnote/blob/5f74ca0b16b01f7daabd125321c9969223470652/examples/news/acknowledge-information.ts#L25

**Comment by Kgeek33** [comment]
D'accord merci. Alors une question, en faisant le code que vous avez tous les 2 indiqué, est-ce que la valeur `acknowledged` sera bien changé ?

Ps: mon code, en faisant `setNewsRead(account, message, true);`
Ça appelle le code suivant :
```
switch (account.service) {
    case AccountService.Pronote: {
      await newsRead(account.instance, message.ref, read);
      break;
    }
```

Qui va exécuté Pawnote et le fichier que vous m'avez envoyé (_c vrai que c'est long_)

**Comment by Gabriel29306** [comment]
Il fait mettre:

```ts
switch (account.service) {
    case AccountService.Pronote: {
      await newsRead(account.instance, message.ref, read);
      await newsInformationAcknowledge(account.instance, message.ref);
      break;
    }
```

**Comment by Kgeek33** [comment]
Ahhhh super merci. J'vais tester cet aprem, après mes cours 😭

**Comment by vexcited** [comment]
@Gabriel29306 le `newsRead` est pas nécessaire, `newsInformationAcknowledge` le fait déjà en interne (cf. le troisième paramètre de la fonction est sur `true` par défaut)

https://github.com/LiterateInk/Pawnote/blob/5f74ca0b16b01f7daabd125321c9969223470652/src/api/news-information-acknowledge.ts#L16

**Comment by Gabriel29306** [comment]
Mais pour les news qui ne demandent que la lecture, pas le "j'ai pris connaissance de l'information", on peut utiliser `newsInformationAcknowledge(session, item);` ?

**Comment by Kgeek33** [comment]
Non je pense pas pask les `acknowledged` doivent rester sur false, vu que la coche n'est pas présente

**Comment by Gabriel29306** [comment]
>    * Will acknowledge the news if needed,
>   * so if the news doesn't need to be acknowledged (`!needToAcknowledge`)
>   * or is already `acknowledged`, we will just do the read step.

> https://github.com/LiterateInk/Pawnote/blob/5f74ca0b16b01f7daabd125321c9969223470652/src%2Fapi%2Fnews-information-acknowledge.ts#L7-L9

On peut l'utiliser sans le `newsRead`.

Mais c'est mieux d'avoir 1 option pour mettre comme lu et une pour valider la réception ("acknowledge")

**Comment by Kgeek33** [comment]
C'est bon de mon côté en tout cas pour cocher, ça marche. 
Je ferai une pr quand j'aurai fini quelques changements d'interfaces (_Spoiler mdr_).

Mais d'abord, révision philo.....

**Comment by godetremy** [comment]
La lecture est intégrée !! C'est le confirmer de Pronote qui n'y est pas !

**Comment by Kgeek33** [comment]
> La lecture est intégrée !! C'est le confirmer de Pronote qui n'y est pas !

Oui, intégré dans ma pr !
