### ISSUE TITLE
Licence absente

### ISSUE THREAD

**Issue by Vilerio** [PapillonApp/papillon-v7#31]
Bonjour,

Je pense qu'une licence serait la bienvenue, pour toutes les raisons qui justifient l'existence de ces dernières ;)
#31

**Comment by tryon-dev** [comment]
Yes on fait cela tout de suite, désolé pour l'oublie

**Comment by vexcited** [comment]
Merci de l'avoir mentionné, j'ai complétement oublié de la push durant la migration.

**Comment by Vilerio** [comment]
Les gars j'ai déjà fait une PR pour ça mdr

**Comment by vexcited** [comment]
J'ai push avant d'avoir vu la PR 💀
