### ISSUE TITLE
[Bug] problème de darkmode

### ISSUE THREAD

**Issue by Awakno** [PapillonApp/papillon-v7#318]
![image](https://github.com/user-attachments/assets/45dd020c-cf2f-4774-8092-58742e84d631)

Petit problème lorsqu'un mail est écrit en noir on ne voit pas les écritures

**Comment by Gabriel29306** [comment]
École directe ? (Tu aurais pu utiliser le modèle 😉)

**Comment by Awakno** [comment]
Désolé

Os: iOS
Plateforme: PRONOTE 
Version de papillon : 7.2.1

**Comment by Kgeek33** [comment]
C'est pas plutôt une image ?

**Comment by Kgeek33** [comment]
OK j'ai rien dit...
Sur Pronote, c'est quoi le rendu ?

**Comment by Awakno** [comment]
J'ai pu accès au mail sur PRONOTE

**Comment by Awakno** [comment]
Ah si c'est bon

![image](https://github.com/user-attachments/assets/ed461540-d27f-4339-b207-a6ec448eca32)

**Comment by Kgeek33** [comment]
merci pour la capture
@Louis-htmlcss t'avais pas fait une PR pour corriger ça ?

**Comment by Louis454545** [comment]
> merci pour la capture
> @Louis-htmlcss t'avais pas fait une PR pour corriger ça ?

Yes mais il l on close car il voulait pas le faire comme ca

**Comment by Kgeek33** [comment]
@Awakno quand tu mets Pronote en mode sombre (_dans les paramètres de l'app, faut être déconnecté_), comment ça s'affiche ?

Je rigole s'il y a le même bug 🤣

**Comment by Gabriel29306** [comment]
Moi jpp tester car ils sont un peu moins con dans mon étab 😂

**Comment by Kgeek33** [comment]
corrigé sur ma PR #325 mais n'affiche plus les couleurs (_en rouge dans ton exemple_)
J'espère que ce n'est pas gênant 😅
