### ISSUE TITLE
[Feature]: Système de plugin

### ISSUE THREAD

**Issue by Aymano200** [PapillonApp/papillon-v7#321]
### Description de la fonctionnalité

Bonjour désolé pour l’utilisation du tag je ne savais pas quoi utiliser d’autre, ce serait bien un tag « Questions » bon bref.
Est-ce que le système de plugin est en cours de développement ou éventuellement d’implémentation dans l’application parce que la fonctionnalité est teasée depuis un certain moment via le site web ou l’application toutefois elle n’as pas l’air d’avoir été codée ou même sa documentation crée. Je me demandais simplement si je pouvais avoir une date/des traces d’avancement de la fonctionnalité 
(PS: Je suis juste hype à pouvoir modifier Papillon en créant/installant des plugins)

### Contexte supplémentaire

N/A

**Comment by Gabriel29306** [comment]
Je crois que cela n'a même pas été commencé, je n'ai pas vu de branche où cette fonctionnalité à té commencée.
(Il se peut que la fonctionnalité soit développée sur un fork)

**Comment by Kgeek33** [comment]
Y a pas les thèmes de la messagerie en temps que plugin ?
Issue -> #262

**Comment by ecnivtwelve** [comment]
Les plug-ins sont développés et fonctionnels depuis le début sur la v7, juste pas actifs car non finalisés : https://github.com/PapillonApp/Papillon/blob/main/src/addons/addons.ts
