### ISSUE TITLE
[Bug]: Widget Vie Scolaire n'affiche pas les horaires injustifiés

### ISSUE THREAD

**Issue by imyanice** [PapillonApp/papillon-v7#347]
### Description du bug

![image](https://github.com/user-attachments/assets/1e18637e-616f-41c5-a69c-eceff010ed13)

### Comportement attendu

00h00 = > 00h05

**Comment by Kgeek33** [comment]
Tu peux montrer la page vie scolaire ?

**Comment by imyanice** [comment]
> Tu peux montrer la page vie scolaire ?

Au fait, je suis entrain de mettre en place le projet Papillon, si tu veux y jeter un coup d'oeuil :)
Et rejoins le discord stp 🙏 

![image](https://github.com/user-attachments/assets/ff124553-16ad-421a-be4b-d5b07a55d418)

**Comment by Kgeek33** [comment]
ok, comme ma pr n'a pas encore été merged, je vais l'inclure dedans :)

**Comment by imyanice** [comment]
> ok, comme ma pr n'a pas encore été merged, je vais l'inclure dedans :)

perfect

**Comment by Kgeek33** [comment]
je vois pas comment faire
tu peux tester ma pr #325 pour me dire si t'as le même problème ? (_comme j'ai restauré l'ancienne page d'accueil_)

**Comment by Kgeek33** [comment]
Et flm pour le Discord, je rencontre tjrs des problèmes avec -_-
Ouii, j'ai vu pour ton projet, je regarde ça en détail tout à l'heure

**Comment by imyanice** [comment]
je m'en occupe c'est bon tkt

**Comment by Kgeek33** [comment]
t'as testé la pr #325 ?
j'ai déjà fait un fix pour mettre les minutes injustifiées en rouge

**Comment by Kgeek33** [comment]
ou pour que je fix, tu rajoutes la ligne ci-dessous et m'envoies les logs :
Fichier : `src/views/account/Home/Elements/AttendanceElement.tsx`

A ajouter (ligne 90) : `console.log(totalMissed, formatTotalMissed(totalMissed));`

**Comment by imyanice** [comment]
> fix pour mettre les minutes injustifiées en rouge

why ???????

**Comment by Kgeek33** [comment]
ben en ce moment, ça disait que si t'as au moins 1h injustifiée, ben en rouge
sinon, ça s'adapte en noir ou blanc

**Comment by Kgeek33** [comment]
pour moi, c'était pas logique, voilà pq

**Comment by imyanice** [comment]
> pour moi, c'était pas logique, voilà pq

oui car c'est en général le moment à partir duquel y'a la vie scolaire qui vient te voir, et perso ça me rendrait dingue de voir mes pauvres 5 minutes en rouge

**Comment by Kgeek33** [comment]
ah ok d'accord :)
Mdrr, une de mes profs, si t'arrives 1 seconde après la sonnerie, 1 min de retard sur pronote 🤣

**Comment by Kgeek33** [comment]
très intéressant le projet Papillon. on a le droit de le modifier ?

**Comment by imyanice** [comment]
> très intéressant le projet Papillon. on a le droit de le modifier ?

il faut que tu dm qqun sur discord
