### ISSUE TITLE
[Enhancement]: Déploiement automatique avec GitHub Action

### ISSUE THREAD

**Issue by maelgangloff** [PapillonApp/papillon-v7#35]
### Description du problème

L'application n'est pas déployée automatiquement sur les stores. En effet, elle est actuellement publiée localement et non via une Action GitHub.

### Description de l'amélioration

Il serait intéressant d'automatiser le déploiement et la publication de l'application. En faisant apparaître les signatures, cela permet de s'assurer que la version dans les stores correspond au code source de ce dépôt GitHub.

**Comment by ecnivtwelve** [comment]
Très bonne idée, ça serait cool de voir ça rapidement ! @yannouuuu des pistes ?

**Comment by vexcited** [comment]
> Très bonne idée, ça serait cool de voir ça rapidement ! @yannouuuu des pistes ?

T'en fais pas qu'il est déjà dessus depuis cet après midi... https://github.com/yannouuuu/Papillon/actions !

**Comment by Rexxt** [comment]
nickel, par contre quand les actions échouent c'est moins nickel

**Comment by Gabriel29306** [comment]
Par contre, il faudrait générer un `apk` pour avoir la release en direct depuis github mais aussi un `aab` pour être release sur les stores.
Et idéalement, avoir un canal release et bêta sur le Play Store (je sais pas comment c'est avec Apple)

**Comment by yannouuuu** [comment]
> nickel, par contre quand les actions échouent c'est moins nickel

ça c'est moi qui doit attendre que @ecnivtwelve me donne ses certificats, hormis ce détail Android fonctionne déjà parfaitement

**Comment by yannouuuu** [comment]
> Par contre, il faudrait générer un `apk` pour avoir la release en direct depuis github mais aussi un `aab` pour être release sur les stores. Et idéalement, avoir un canal release et bêta sur le Play Store (je sais pas comment c'est avec Apple)

Pour le aab t'as raison je vais modifier ça. Et pour le canal j'ai ma petite idée de comment l'intégrer 👌😊

**Comment by maelgangloff** [comment]
> ça c'est moi qui doit attendre que @ecnivtwelve me donne ses certificats, hormis ce détail Android fonctionne déjà parfaitement

Pitié faites en sorte que les clés privées ne soient connus de **personne** hormis le détenteur du compte et les secrets GitHub pour le déploiement automatique.

**Comment by Rexxt** [comment]
on est ptet pas tant intelligents que ça mais quand même 🤨

**Comment by yannouuuu** [comment]
En tout cas lui n'a pas eu l'intelligence d'aller voir mon repo pour voir comment j'ai fait 🫥

**Comment by Rexxt** [comment]
balle perdue

**Comment by oriionn** [comment]
C'est pas une balle perdue, c'est une balle méritée

**Comment by tom-theret** [comment]
@yannouuuu, ta méthode est bien si tu fais que Android, mais il est préférable d’utiliser expo local.

**Comment by tryon-dev** [comment]
skill issue
