### ISSUE TITLE
Calcule de la moyenne générale de classe 

### ISSUE THREAD

**Issue by Quentin-17** [PapillonApp/papillon-v7#359]
### Description de la fonctionnalité

On pourrait implémenter le faite que papillon récupère la moyenne générale de la classe de pronote via pawnote.

**Comment by ecnivtwelve** [comment]
C'est déja le cas ? https://github.com/PapillonApp/Papillon/blob/681651d06fd482af28016b3d83072fe981e1d4b3/src/utils/grades/getAverages.ts#L148-L152

**Comment by Kgeek33** [comment]
Oui eft, c'est juste le bug de l'issue #356, qui calcule tout le temps la moyenne de la classe alors qu'elle est disponible

**Comment by Quentin-17** [comment]
> Oui eft, c'est juste le bug de l'issue #356, qui calcule tout le temps la moyenne de la classe alors qu'elle est disponible 

Oui c'est ça 👍 et ducoup ça affiche une moyenne de classe différente de la moyenne réelle
