### ISSUE TITLE
[Enhancement]: Enlever moyenne haute basse ed

### ISSUE THREAD

**Issue by Nicolasfr340** [PapillonApp/papillon-v7#366]
### Description du problème

Le problème est que quand on clique sur la moyenne, on obtient un menu déroulant « moyenne max » et « moyenne min »
Le truc étant que c’est obtenu en faisant la moyenne des moyennes les plus hautes et la moyenne des moyennes les plus basses (avec le système d’EcoleDirecte), mais personne n’a la moyenne la plus haute dans toutes les matières, ni l’inverse 

ce qui fait que on voit une moyenne max de 19.51, disons que c’est perturbant et qu’on a tendance à se remettre en question 

### Description de l'amélioration

Les enlever du menu quand c’est via EcoleDirecte
![IMG_9657](https://github.com/user-attachments/assets/6c5bdf98-568c-405d-8171-2bc380167228)

**Comment by Kgeek33** [comment]
Alors davantage de détails ont été apporté sur la pr #363
Cependant, comme j'en ai parlé sur #355, je trouve que cette fonctionnalité est inutile car déjà c'est du calcul, donc c'est forcément que ça n'existe pas (une moyenne des meilleures moyennes par matière) et peu de personnes connaissent cette fonctionnalité, peu d'indication

**Comment by imyanice** [comment]
Ça fait la moyenne de toutes les moyennes les plus hautes de toute les évaluations. Donc techniquement, c'est la moyenne la plus haute dans toutes TES matières, après ça ne prend pas en compte la moyenne par classe (ex: groupe de spécialités)

**Comment by ecnivtwelve** [comment]
J'ai récemment fait une PR (https://github.com/PapillonApp/Papillon/pull/363) qui adresse ce problème, afin d'indiquer clairement l'origine des chiffres, et ce pour tous les utilisateurs.
