### ISSUE TITLE
Couleur actualités 

### ISSUE THREAD

**Issue by Cleboost** [PapillonApp/papillon-v7#367]
### Description du problème

Les couleurs des actualité ne marchent pas avec le thème sombre 

### Description de l'amélioration

Changer la couleur du texte en fonction du thème ui

### Contexte supplémentaire

![Screenshot_20241115_121053_Papillon](https://github.com/user-attachments/assets/d38997fd-470e-4240-8b7f-839f2a34991f)

**Comment by Kgeek33** [comment]
Je l'ai changé sur ma pr #325 en changeant de librairie

**Comment by Cleboost** [comment]
Okay !
