### ISSUE TITLE
[Feature]: Service cantine scolaire

### ISSUE THREAD

**Issue by Cleboost** [PapillonApp/papillon-v7#381]
### Description de la fonctionnalité

Une intégration pour un nouveau système de restauration, je sais pas si c'est prévus d'en rajouter :)

![image](https://github.com/user-attachments/assets/0cc06f0a-f98f-4385-959f-d89a8ce816fb)
![image](https://github.com/user-attachments/assets/978773c5-6c16-4d8d-93c7-9822c8dd0f77)

**Comment by Gabriel29306** [comment]
Tu pourrais nous décrire un peu plus ton service, il a un nom ?

**Comment by tom-theret** [comment]
Je viens de faire une brève recherche je suis tombé sur ça : [https://resto-scolaire.fr/](https://resto-scolaire.fr/).
On dirait un truc maison

**Comment by Cleboost** [comment]
Je viens de me renseigner. C'est un truc maison...

**Comment by tryon-dev** [comment]
Alors on a déja essayer et malheureusement il y a un capcha qui bloque tout donc faut voir

**Comment by codeuriii** [comment]
Je peux peut etre aider, comment on peut faire ?

**Comment by Christian-Martins** [comment]
> Alors ont a déja essayer est malheureusement il y a un capcha qui bloque tout donc faut voir

La seule solution envisageable c'est d'avoir le captcha qui s'affiche, et que l'utilisateur doit l'effectuer à chaque connexion à resto scolaire (envisager du cache etc. mais ça reste pas optimal)

**Comment by codeuriii** [comment]
Il y a des extensions web qui permettent de résoudre des petit captcha style hcaptcha et recaptcha sans trop de problèmes. Il faudrait avoir le code source ou rétroingenirer l'app

**Comment by Cleboost** [comment]
Je penses que le mieux c'est d'afficher une captcha à l'utilisateur. Ça me semble plus éthique que bypass avec des extensions ou je sais pas quoi.

**Comment by codeuriii** [comment]
Sauf que ca va être crade pour papillon

**Comment by raphckrman** [comment]
> Je penses que le mieux c'est d'afficher une captcha à l'utilisateur. Ça me semble plus éthique que bypass avec des extensions ou je sais pas quoi.

Comment tu veux l'intégrer pour que ce soit beau ? Et le problème sera au moment de reload le compte, compléter à chaque fois un captcha devient vite chiant

**Comment by raphckrman** [comment]
> Je penses que le mieux c'est d'afficher une captcha à l'utilisateur. Ça me semble plus éthique que bypass avec des extensions ou je sais pas quoi.

Comment tu veux l'intégrer pour que ce soit beau ? Et le problème sera au moment de reload le compte, compléter à chaque fois un captcha devient vite chiant

**Comment by Cleboost** [comment]
Oui mais est ce que légalement on a le droit de le bypass ? Surtout que tout ces systèmes de bypass marchent de moins en moins car ils sont de plus en plus compliqué (hcapchta par exemple)

**Comment by codeuriii** [comment]
On peut toujours essayer

**Comment by Kgeek33** [comment]
Il n'existe pas une api pour éviter d'avoir un captcha ?

**Comment by codeuriii** [comment]
Faut chercher, au pire retroingeniere l'extension du truc

**Comment by tom-theret** [comment]
Mais leur lycée on aussi turboself visiblement
