### ISSUE TITLE
Intégration MyTurboself

### ISSUE THREAD

**Issue by Devantho** [PapillonApp/papillon-v7#384]
### Description de la fonctionnalité

Bonjour dans mon lycée la cantine fonctionne avec MyTurboself, ça serait bien de l’intégrer au système de cantine sous forme de plugin ou quelque choses comme ça, j’ai vu un projet qui utilisé une api MyTurboSelf donc ça doit être possible je pense.

**Comment by tom-theret** [comment]
Bonjour, Turboself est déjà pris en charge. 
Il faut aller dans les paramètres puis comptes externes.

**Comment by raphckrman** [comment]
Salut, Turboself est déjà intégré, plus d'informations ici: https://github.com/PapillonApp/Papillon/pull/277

**Comment by totchi-lagawi** [comment]
La pull request n'est apparemment pas passée dans la version 7.3.0, plus qu'à attendre la 7.4.0...

**Comment by Kgeek33** [comment]
En attendant, vous avez la version 7.5.0 qui est disponible sur le play store /test flight en version beta (une version stable prévue plus tard) 
Cependant, un bug connu de cette version est que la coche des devoirs ne s'affiche plus

**Comment by Devantho** [comment]
Bonjour pour service externe je vois la fonctionnalité grise avec marqué prochainement j'imagine qu'il faut attendre la maj. Merci
Edit: effectivement sur TestFlight ça fonctionne.
