### ISSUE TITLE
[Enhancement]: Support des liens dans les devoirs

### ISSUE THREAD

**Issue by totchi-lagawi** [PapillonApp/papillon-v7#385]
### Description du problème

Certains professeurs mettent des liens dans les devoirs. Le problème est que le texte n'est pas cliquable, il faudrait donc ajouter cette fonctionnalité.

### Contexte supplémentaire

![Screenshot_20241125-222542](https://github.com/user-attachments/assets/43dedc39-f357-4ceb-9897-1f35dca62af0)
![Screenshot_20241125-222614](https://github.com/user-attachments/assets/6cd3a3bc-2917-4a88-8525-b8a9ceef2f81)

**Comment by Kgeek33** [comment]
C'est une bonne idée !
Mais est-ce sur Pronote ou autre, ce lien est cliquable ? Si non, ça peut être plus compliqué à être intégré

**Comment by totchi-lagawi** [comment]
Le lien est bien cliquable sur l'application Pronote.

**Comment by Kgeek33** [comment]
OK ben je fais voir avec la librairie qui affiche les devoirs si c'est possible
Pour m'aider, tu peux faire une capture d'écran de ton devoir sur Pronote stp ?

**Comment by totchi-lagawi** [comment]
Le lien n'est en fait cliquable qu'en appuyant sur le devoir.

**Comment by Kgeek33** [comment]
OK d'accord
Sur la version 7.5.0 disponible en version beta, j'ai fait un changement sur l'affichage des devoirs. Faut que je regarde si les liens dans les devoirs peuvent être ouverts en cliquant dessus

**Comment by Kgeek33** [comment]
@totchi-lagawi est-ce toujours à intégrer ? Une nouvelle version de Papillon est disponible en production (7.5.0)

**Comment by totchi-lagawi** [comment]
Les liens ne sont pas supportés dans la nouvelle version.

**Comment by Kgeek33** [comment]
Ok très bien, je ferai une pr pour intégrer ça

**Comment by Clmnnt** [comment]
@Kgeek33 Possible de le mettre en PJ même si il est directement dans les devoirs et pas en PJ du devoir?

**Comment by Kgeek33** [comment]
> @Kgeek33 Possible de le mettre en PJ même si il est directement dans les devoirs et pas en PJ du devoir?

oui, je pense faire ça, c'est ce que fait Pronote quand un lien est intégré

**Comment by Kgeek33** [comment]
L'issue peut être closed! Ça a été fait dans #412

**Comment by Kgeek33** [comment]
@totchi-lagawi sur la version 7.6.0 de Papillon, rencontres-tu encore ce problème ?

**Comment by totchi-lagawi** [comment]
Je n'arrive pas à trouver la version 7.6.0 T-T
Le Play Store indique toujours que la dernière est la 7.5.0...

**Comment by LeGeek01** [comment]
la 7.6.0, si elle a été envoyée, n'a pas encore été acceptée par google du fait de leurs délai, devenus maintenant extrêmement long

**Comment by Kgeek33** [comment]
> la 7.6.0, si elle a été envoyée, n'a pas encore été acceptée par google du fait de leurs délai, devenus maintenant extrêmement long

C'est vrmt bizarre, on me l'a proposé tout à l'heure
![Screenshot_2024-12-14-15-28-01-952_com.android.vending.jpg](https://github.com/user-attachments/assets/6dd6f6bd-2cff-49ca-a2af-9533db112ea5)

![Screenshot_2024-12-14-15-28-21-237_com.android.vending.jpg](https://github.com/user-attachments/assets/f2dc935e-d689-47d3-972e-d8c0759863be)

**Comment by totchi-lagawi** [comment]
J'ai pris la version bêta, avec l'ancienne page d'accueil, mais je n'ai toujours pas la version 7.6.0...

**Comment by Kgeek33** [comment]
> J'ai pris la version bêta, avec l'ancienne page d'accueil, mais je n'ai toujours pas la version 7.6.0...

Ah alors patiente encore ou sinon, t'as l'apk dans les releases de Github

**Comment by totchi-lagawi** [comment]
Toujours pas de support...
