### ISSUE TITLE
Ajout des groupes dans l’emploi du temps

### ISSUE THREAD

**Issue by Devantho** [PapillonApp/papillon-v7#397]
### Description du problème

Il faudrait ajouter les groupes pour savoir si l’on est en demi classe ou pas, dans l’emploi du temps merci

### Description de l'amélioration

Il faudrait ajouter les groupes pour savoir si l’on est en demi classe ou pas, dans l’emploi du temp merci
Exemple en PJ du groupe «207G2 »
![Uploading IMG_3807.jpeg…]()

**Comment by codeuriii** [comment]
l'image est pas passée.
de plus c'est "temps"

**Comment by Kgeek33** [comment]
oui effectivement, l'image n'est pas passée
sinon, c'est déjà intégré mais pour voir ça, il faut cliquer sur la matière.
il faudrait donc l'afficher sans forcément cliquer sur la matière ?

**Comment by codeuriii** [comment]
peut etre close cette issue du coup vu que y a déjà les groupes sur la matière non ? jsp du tout

**Comment by Kgeek33** [comment]
Jspas, c'est pour ça que je posais la question s'il faut afficher le groupe directement sur l'emploi du temps sans avoir à cliquer sur la matière
S'il y a pas besoin, alors l'issue peut être closed

**Comment by tom-theret** [comment]
Pas besoin, c'est pas une information primordiale.

Du coup on peut close l'issue

**Comment by Clmnnt** [comment]
C’est pas dans classes les groupes ?

**Comment by Clmnnt** [comment]
ah j’ai rien dit mb y’a pas les classes

**Comment by Clmnnt** [comment]
Je les ai les groupes???

**Comment by codeuriii** [comment]
Pourquoi c'est pas close ?

**Comment by Kgeek33** [comment]
@Clmnnt les groupes sont indiquées sur une matière (_donc en cliquant dessus_) que quand t'as pas cours en classe entière ou quand le cours de déroule avec plusieurs classes

**Comment by Kgeek33** [comment]
@codeuriii c'est à @Devantho ou à l'équipe de Papillon de close cette issue
