### ISSUE TITLE
[BUG] : Moyenne générale

### ISSUE THREAD

**Issue by Nono-archi** [PapillonApp/papillon-v7#411]
Si une matière est Non Noté le calcul de la moyenne comprend zero se qui donne une moyenne totalement fausse

**Comment by Kgeek33** [comment]
Sur le graphique tu parles ?

**Comment by mfr4y** [comment]
> Sur le graphique tu parles ? 

Non juste en général si on a une note non notée ça nous compte un 0 dans le calcul de la moyenne générale

**Comment by Nono-archi** [comment]
Je ne crois pas j'avais aussi eu un Non Noté dans Pronote l'année dernière et sa n'avais juste pas compté dans la moyenne (quand j'avais encore la moyenne 😅)

**Comment by mfr4y** [comment]
> Je ne crois pas j'avais aussi eu un Non Noté dans Pronote l'année dernière et sa n'avais juste pas compté dans la moyenne (quand j'avais encore la moyenne 😅)

Parce que sur Pronote un non-noté ne compte pas dans la moyenne ce qui est normal 
mais sur Papillon un non noté compte 0 ce qui fausse la moyenne

**Comment by Kgeek33** [comment]
Bizarre, de base, quand t'as N. Noté ou autres raisons (Abs, Disp...), ça renvoie -1/20
Mais c'est en cours de travail, l'issue est presque en lien avec #353

**Comment by mfr4y** [comment]
> Bizarre, de base, quand t'as N. Noté ou autres raisons (Abs, Disp...), ça renvoie -1/20
> Mais c'est en cours de travail, l'issue est presque en lien avec #353 

pas possible de return null pour que ça compte pas un n. noté ?

**Comment by Kgeek33** [comment]
Faut voir avec @ecnivtwelve sur l'évolution de l'autre issue en rapport avec celle ci
