### ISSUE TITLE
[Enhancement]: Fixer la template des Pull Requests

### ISSUE THREAD

**Issue by ecnivtwelve** [PapillonApp/papillon-v7#42]
### Description du problème

La template des PR (https://github.com/PapillonApp/Papillon/compare) ne fonctionne pas correctement.

### Description de l'amélioration

Il faudrait que le template soit modifié pour fonctionner correctement.

**Comment by yannouuuu** [comment]
Already fix [#41b9a45](https://github.com/PapillonApp/Papillon/commit/41b9a45a3eedc1c820d57729bd698044e10a4748)
