### ISSUE TITLE
[Enhancement]: Lien vers les instructions pour collaborer au projet

### ISSUE THREAD

**Issue by thebrainfox44** [PapillonApp/papillon-v7#425]
### Description du problème

sur github, à la fin du readme le lien vers la docu pour les devs qui veulent collaborer redirige vers une page invalide (https://developers.papillon.bzh/getting-started/quick-start)

### Description de l'amélioration

Mettre le nouveau lien (https://developers.papillon.bzh/) à la place

**Comment by Gabriel29306** [comment]
Déjà corrigé, à close.
