### ISSUE TITLE
[Enhancement]: pas d'affichage repas du soir

### ISSUE THREAD

**Issue by TortocheTV** [PapillonApp/papillon-v7#430]
### Description du problème

Bonjour, j'ai pu remarquer que dans l'onglet cantine il n'y a pas d'affichage pour le repas du soir également pouvez-vous faire comme dans l'agenda pour changer la date du menu en swipe
![Screenshot_2024-12-13-09-05-57-467_xyz getpapillon app](https://github.com/user-attachments/assets/3e2e0d04-6836-4fee-a203-11292a7d3805)
 vers la droite ou la gauche

### Description de l'amélioration

Mettre une option pour choisir entre repas du jour et repas du soir pour les internes et faire pour pouvoir changer de jour de repas en swipe vers la droite et la gauche

**Comment by Kgeek33** [comment]
@TortocheTV sur la version 7.6.0 de Papillon, rencontres-tu encore ce problème ?

**Comment by TortocheTV** [comment]
Bonjour, oui il y a toujours le problème également le problème a l'accueil quand on swipe est revenu l'animation bug 
![Screenshot_2024-12-14-13-30-45-026_xyz getpapillon app](https://github.com/user-attachments/assets/d4cc03c8-ce4b-4279-8cf8-631760ab70dd)

**Comment by TortocheTV** [comment]
Voici ce qu'il y a sur le Pronote de base 

![Screenshot_2024-12-14-13-35-50-827_com IndexEducation Pronote](https://github.com/user-attachments/assets/f0d9dfe6-f991-45f2-a26c-1130ef33df89)
![Screenshot_2024-12-14-13-35-54-780_com IndexEducation Pronote](https://github.com/user-attachments/assets/75ac1b91-8b3a-49fd-9f46-004f14147ccd)

**Comment by Kgeek33** [comment]
Bonjour, faut voir avec @raphckrman si l'intégration est possible
Pour la page d'accueil, et oui, personne ne veut approuver ma pr qui fait un revert de la page d'accueil... (voir #372). 
J'essaye de fix plutôt qu'un revert (comme demandé par @godetremy) aujourd'hui

**Comment by raphckrman** [comment]
Le menu du soir est integre j'ai fait une PR, je vais voir pour le swipe

**Comment by Kgeek33** [comment]
> Le menu du soir est integre j'ai fait une PR, je vais voir pour le swipe 

Si t'arrives à trouver une solution pour le swipe, fais moi signe dans ma pr #372 stp :)
Indice : C'est le `interpolate` qui est mal géré

**Comment by raphckrman** [comment]
> > Le menu du soir est integre j'ai fait une PR, je vais voir pour le swipe
> 
> Si t'arrives à trouver une solution pour le swipe, fais moi signe dans ma pr #372 stp :) Indice : C'est le `interpolate` qui est mal géré

yes je l'ai surtout pas intégré pour l'instant mais c'est prévu

**Comment by Kgeek33** [comment]
@raphckrman @TortocheTV j'ai corrigé pour la page d'accueil, elle est un peu plus stable
=> Voir #372

**Comment by Kgeek33** [comment]
@raphckrman ça a été intégré du coup les repas du soir ?

**Comment by raphckrman** [comment]
oui
