### ISSUE TITLE
Version Web ou locale pour Ordinateur

### ISSUE THREAD

**Issue by OrangeZXZ** [PapillonApp/papillon-v7#435]
### Description de la fonctionnalité

Une version web ou installable de l'application serait bien.

### Contexte supplémentaire

Ceci évitera la consultation de Pronote ou de l'ENT sur téléphone en classe.

**Comment by Gabriel29306** [comment]
Alors, web c'est non, CORS.
Pour ce qui est d'une version PC, ce n'est pas une priorité !
