### ISSUE TITLE
[Enhancement]: ios 18 icon

### ISSUE THREAD

**Issue by JyhuKo** [PapillonApp/papillon-v7#439]
### Description du problème

ajouter l'icon compatible ios18

### Description de l'amélioration

ajouter l'icon compatible ios18

### Contexte supplémentaire

ajouter l'icon compatible ios18

**Comment by raphckrman** [comment]
c'est à dire l'icon compatible iOS 18 ?

**Comment by noebrl** [comment]
tu parles du mode sombre sur l'icone ?

**Comment by Kgeek33** [comment]
Je pense que c'est ça, uen icône spéciale pour le mode sombre

**Comment by JyhuKo** [comment]
oui exact

**Comment by ecnivtwelve** [comment]
Elle y est déjà, c'est juste qu'elle se fait écraser au build et que je ne pense pas toujours à la réappliquer
