### ISSUE TITLE
[Enhancement]: Graphique Moyenne Générale

### ISSUE THREAD

**Issue by ForTyxx13** [PapillonApp/papillon-v7#442]
### Description du problème

Ça n'est pas vraiment un problème.

### Description de l'amélioration

L'amélioration qui peut être faite est de préciser le graphique de moyenne générale journée après journée pour suivre l'avancée petit à petit. Par exemple suivre la moyenne sur une période ou sur un jour spécifique.

**Comment by ecnivtwelve** [comment]
A moins d'avoir des notes à une fréquence très très régulière, je ne vois pas de situation ou cela peut être utile...

**Comment by Gabriel29306** [comment]
Pas de nouveautés sur l'issue.
À close.
