### ISSUE TITLE
Bug cours du lendemain 

### ISSUE THREAD

**Issue by mfr4y** [PapillonApp/papillon-v7#464]
Le dimanche ça note sur la page d'accueil « aucun cours a venir pour les prochains jours » alors qu'on est dimanche et que lundi j'ai bien des cours de prévu

et faire en sorte quand on clique sur les « cours » dans la navbar du bas et que c'est le weekend ou un jour il y a pas cours, mettre le jour le plus proche où il y a cours

![Screenshot_20241215_173700_Papillon.png](https://github.com/user-attachments/assets/cd62856e-2c72-4d0b-9e03-662523f40c75)

Pareil pour les devoirs, le weekend ça met les devoirs de la semaine qui est passé (exemple là, la semaine 15 est passée et ça me met les devoirs de la semaine 15 au lieu des devoirs de la semaine 16)

**Comment by Kgeek33** [comment]
- Sur l'emploi du temps de la page d'accueil, corrigé dans #459
- Pour les devoirs sur la page d'accueil, amelioré dans #372
- Pour les devoirs sur la navbar, corrigé dans #461
