### ISSUE TITLE
[Feature]: Bug report

### ISSUE THREAD

**Issue by JyhuKo** [PapillonApp/papillon-v7#467]
### Description de la fonctionnalité

pas sur qu'il y ai déjà mais ajouter un bouton quelque part pour signaler un bug / demander une fonctionnalité (comme ici en gros)  dans l'application car tout le monde ne sait pas qu'il faut aller sur le github pour cela

### Contexte supplémentaire

-

**Comment by noebrl** [comment]
vu le nombre de demandes sur github et discord c'est peut être un peu overkill de pouvoir demander une fonctionnalité si facilement.
