### ISSUE TITLE
[Enhancement]: Couleur du menu complètement personnalisable 

### ISSUE THREAD

**Issue by lavalmc** [PapillonApp/papillon-v7#468]
### Description du problème

Seulement 6 couleurs de base (je crois)

### Description de l'amélioration

Je voudrais que les couleurs qu'on peut sélectionner de base soit complètement personnalisable (sélection de couleur personnalisé)

**Comment by noebrl** [comment]
la suggestion a déjà été faite et prise en compte

**Comment by lavalmc** [comment]
> la suggestion a déjà été faite et prise en compte

C'est sur quelle numéro l'issue ?

**Comment by noebrl** [comment]
> > la suggestion a déjà été faite et prise en compte
> 
> C'est sur quelle numéro l'issue ?

https://discord.com/channels/1014931881906675712/1317268950756622397

j'ai vu passé ça sur discord, je pensais qu'y avait une pr de faite dsl
