### ISSUE TITLE
[Enhancement]: Une version windows ?

### ISSUE THREAD

**Issue by ErterlinkOff** [PapillonApp/papillon-v7#479]
### Description du problème

it aint a problem

### Description de l'amélioration

une version windows, même navigateur,  serai la bienvenue, car c'est pas discret de checker son tel 5 fois par cours pour voir les belles animations de Papllilon

**Comment by Bulgus** [comment]
_(Du discord)_

> Il n'y aura aucun Papillon Web car il faut passer par des serveurs tiers et ça ne respecte pas la loi et les RGPD car nous affichons des données sensibles. Un client Windows a déjà été abordé
> Mais il a été décidé que ce n'est pas la priorité et que ceci répond à une très petite partie des utilisateurs

Un client mac os existe déjà (edit : que sous puce Silicon), windows n'est pas la prio ! Et pour le web, impossible pour des raisons légales...

**Comment by oriionn** [comment]
> _(Du discord)_
> 
> > Il n'y aura aucun Papillon Web car il faut passer par des serveurs tiers et ça ne respecte pas la loi et les RGPD car nous affichons des données sensibles. Un client Windows a déjà été abordé
> > Mais il a été décidé que ce n'est pas la priorité et que ceci répond à une très petite partie des utilisateurs
> 
> Un client mac os existe déjà, windows n'est pas la prio ! Et pour le web, impossible pour des raisons légales...

Un client Mac OS existe que pour les macs avec puce Silicon* (c'est la version iPad quoi)

**Comment by Mewax07** [comment]
Je suis passionner de programmation web et il est possible de le faire un client windows je n'ai pas encore étudier le fait de publier légalement une version donc pour l'instant sa reste juste un projet pour m'améliorer mais peut être que sa sortira

**Comment by ErterlinkOff** [comment]
ce serai super, l'ordi région est déléssé

**Comment by ErterlinkOff** [comment]
@oriionn, l'emulation est une option ? une emulation de ipad os sur bluestacks ?

**Comment by oriionn** [comment]
> ce serai super, l'ordi région est déléssé

Ce n'est pas un choix c'est surtout une fonction par défaut quand on a une application iOS, on peut l'utiliser sur Mac M1 (et les autres puces silicon)

**Comment by oriionn** [comment]
> @oriionn, l'emulation est une option ? une emulation de ipad os sur bluestacks ?
> 

Tu fais comme tu veux, émuler iPad OS sur Bluestacks c'est certainement pas possible, mais émuler une tablette Android oui.

Mais ça risque d'être instable et consommer beaucoup de ressources pour pas grand chose.

**Comment by oriionn** [comment]
> Je suis passionner de programmation web et il est possible de le faire un client windows je n'ai pas encore étudier le fait de publier légalement une version donc pour l'instant sa reste juste un projet pour m'améliorer mais peut être que sa sortira

Oui on sait très bien que c'est possible de faire un client, mais pour rappel si on fait ça fait maintenir le projet etc. Déjà que l'application mobile a plein de bug pas encore patché, on va pas se lancer dans la maintenance d'un client PC.

**Comment by Kgeek33** [comment]
https://github.com/PapillonApp/Papillon/pull/533#issuecomment-2558490229

**Comment by yannouuuu** [comment]
Papillon n'a jamais eu pour but d'avoir une application desktop que ce soit pour Windows, MacOS, ou Linux!
