### ISSUE TITLE
[Feature]: PRONOTE + Skolengo

### ISSUE THREAD

**Issue by WyxZer** [PapillonApp/papillon-v7#489]
### Description de la fonctionnalité

Bonjour,
Dans mon établissement, les profs mettent les devoirs sur l’ent (skolengo) et l’emploi du temps et les notes sont sur PRONOTE.

**Il serait très pratique de pouvoir ajouter le compte skolengo dans l’onglet services externes et de choisir quels onglets est lié a quels comptes **
Ce serait plus simple que de devoir avoir 2 comptes dont 1 utilise seulement pour les devoirs.

Maxence.

### Contexte supplémentaire

Dans le paramètre des onglet ajouter l’option de choisir le compte si un autre est lié

**Comment by tom-theret** [comment]
Salut, je comprends ta frustration. Cependant, Skolengo et PRONOTE sont tous les deux des comptes primaires. Par conséquent je ne vois pas l'intérêt mise à part ergonomique de transformer PRONOTE en compte secondaire quand c'est Skolengo qui est utilisé. Ça crée trop de bugs.

**Comment by ftplv** [comment]
> Salut, je comprends ta frustration. Cependant, Skolengo et PRONOTE sont tous les deux des comptes primaires. Par conséquent je ne vois pas l'intérêt mise à part ergonomique de transformer PRONOTE en compte secondaire quand c'est Skolengo qui est utilisé. Ça crée trop de bugs.

Ce n'est malheureusement pas un cas isolé, plusieurs établissements utilisent Skolengo et Pronote de concert.

Ici : 
Devoirs => Skolengo
Notes => Pronote
Actualité => Skolengo 
Vie scolaire => Pronote 
Messages => Skolengo 
Cours => Les 2 mais Pronote prime
Cantine => En pièce jointe des actualités sur Skolengo, pièce jointe qui n'apparaissent pas sur Papillon mais c'est un autre problème.

Ce n'est certes pas la priorité mais il pourrait être pertinent un jour d'avoir une page d'accueil où l'on peut sélectionner le service que l'on souhaite utiliser pour chaque catégorie quand plusieurs comptes primaires sont détectés.

**Comment by raphckrman** [comment]
Je doute que l'architecture actuel de l'application permette la réalisation de cette idée de manière stable. Après à voir si les autres pensent que c'est possible de faire ça de façon stable

**Comment by yannouuuu** [comment]
Ca fait l'objet d'un projet en cours chez [LiterateInk](https://github.com/LiterateInk), malheureusement Papillon ne disposera pas de cette possibilité puisque sa structure ne le permet pas (+ React Native va difficilement aider).
