### ISSUE TITLE
[Enhancement]: Thème sombre/clair

### ISSUE THREAD

**Issue by fraecar** [PapillonApp/papillon-v7#490]
### Description du problème

Salut, je propose de pouvoir ajouter dans les paramètre de l'application, un option qui nous permet de choisir entre thème sombre/clair

### Description de l'amélioration

cette option dans les paramètre permet de choisir quel affichage on veut, en effet, j'utilise principalement le mode sombre dans la plupart des applications, hors sur certaine application je préfère le mode claire pour améliorer la lisibilité des textes
Est ce que sa serait possible de rajouter une option qui permet de choisir le thème (clair/sombre) par un select menu avec les options :
-mode sombre
-mode clair
-thème par défaut du système

merci par avance

**Comment by yannouuuu** [comment]
Bonne idée!

**Comment by raphckrman** [comment]
> Bonne idée!

C'est déjà le cas depuis peu, quelqu'un a déjà fait une PR![image](https://github.com/user-attachments/assets/6bda21e5-f784-4d2f-8185-fd34b20f2c66)

**Comment by Gabriel29306** [comment]
Ah oui, ça date d'il y a moins d'une semaine, je ne l'ai pas dans mon build

**Comment by yannouuuu** [comment]
Elle a été merge ???

**Comment by Gabriel29306** [comment]
Oui, mais petit problème, on a un message `Redémarrer l'application` qui est indiqué lors du changement de mode.
Mais avec la façon dont est dit `Redémarrer l'application`, j'ai bêtement essayé de cliquer dessus alors que ce n'est pas cliquable

**Comment by Gabriel29306** [comment]
De plus le code de la page aurait pû, et aurait dû, être plus optimisé avec une liste pour les check box.
Créer un component juste pour une page n'est pas utile

**Comment by Gabriel29306** [comment]
@godetremy j'ai testé ta fonctionnalité, j'ai quelques soucis sur ta page.
En mode clair, le texte de l'infobulle (on dit ça comme ça ?) reste en blanc, donc illisible
Et je ne sais si c'est facilement faisable, mais ce serait de faire comme avec le toggle system où l'app change instantanément de thème de couleurs (peut être avec une propriété sur la personnalisation du compte ?)

**Comment by Kgeek33** [comment]
déjà merged dans une pr
@Gabriel29306 j'te recommande de faire une nouvelle issue
