### ISSUE TITLE
[Bug]: taille case Travail A Faire trop grande

### ISSUE THREAD

**Issue by JyhuKo** [PapillonApp/papillon-v7#498]
### Description du problème

sur la page d'accueil dans travail a faire les cases de texte sont trop grandes

### Description de l'amélioration

les ajuster a la taille du texte

### Contexte supplémentaire

j'ai fais un petit dessin pour montrer
![image](https://github.com/user-attachments/assets/d12dbe06-f07d-4aa9-94a0-ec2fc9f8f0b8)

**Comment by yannouuuu** [comment]
Alors c'est plus un bug pour le coup TT

**Comment by Kgeek33** [comment]
En lien avec #515, je link l'issue à une PR
