### ISSUE TITLE
[Enhancement]: Faire le tri des issues

### ISSUE THREAD

**Issue by JyhuKo** [PapillonApp/papillon-v7#499]
### Description du problème

ya des issues ouvertes depuis aout et je penses qu'elles ont été résolues 

### Description de l'amélioration

fermer ce qui a été fait / résolu

**Comment by Kgeek33** [comment]
C'est plus qu'une bonne idée ! 😂

**Comment by codeuriii** [comment]
ils veulent pas de modos github, ca leurs fais trop peur, du coup ca séternise

**Comment by Kgeek33** [comment]
> ils veulent pas de modos github, ca leurs fais trop peur, du coup ca séternise

Ok je vais faire une pr qui ajoute un point virgule sur un fichier et je link toutes les issues anciennes 😂😂

**Comment by codeuriii** [comment]
pas mal mdr

**Comment by JyhuKo** [comment]
tres bonne idée

**Comment by Kgeek33** [comment]
Le temps que je prépare ça (illarant 😂), pouvez-vous me lister toutes les issues à closed (donc celles qui sont pas link par une pr) ? Les duplications d'issues sont également à closed

Je pensais à link toutes les issues dans une pr, comme ça ça les ferme toutes et on les recrée après pour bien faire un tri (mais ça se fait pas pour les propriétaires des issues quoi)

**Comment by codeuriii** [comment]
je met pas celle qui ont des pr associées et je garde celle que je pense intéressantes
essaye de regarder ca:
#40
#46
#48
#151 ?
#153 
#159 
#291 
#300 
#319 
#321 
#334 
#353 
#381 
#383 
#386 
#398

**Comment by raphckrman** [comment]
#381 On avait déjà regardé mais ça me semble pas vraiment réalisable à cause du captcha

**Comment by raphckrman** [comment]
#383 J'avais déjà regardé et je doute que l'architecture actuel de l'application permette de réaliser cette fonctionnalité de manière totalement stable mais il faut regarder

**Comment by raphckrman** [comment]
#398 On ne peut rien y faire, il faudrait que ARD se bouge et configure correctement leur certificat

**Comment by raphckrman** [comment]
Sinon le reste oui il faut regarder ça fait un moment qu'elles sont ouvertes

**Comment by Kgeek33** [comment]
ok très bien merci d'avoir pris du temps !
je ferai ça dans le week-end et je vous tiens au courant ;)

D'ici là, vous pouvez tjrs me proposer des issues à close !

**Comment by Kgeek33** [comment]
J'ai commencé à link des issues sur une pr, je continue tout à l'heure
Vous pourriez me (re) faire la liste des issues à close svp pour m'aider ?

**Comment by Skythrew** [comment]
Hello ! D'abord Joyeux Noël :smile: Ensuite j'ai passé un peu de temps à lire les diverses issues et voilà la liste que j'ai pour les issues à close:

#541 
#476
#464 ( à lier avec des PR ? )
#442 
#321 
#520 (duplicata)

Et dans les issues un peu ambigües:

#448 ( Peut-être voir pour le support ?? Mais la priorité n'est pas là)
#329 ( à éclairer mais je suis assez d'accord avec Tom, l'EDT doit être intègre et le flou sur le nom des profs peut devenir gênant)

**Comment by Kgeek33** [comment]
Salut, Joyeux Noël ! Merci pour les issues, je les link de suite

**Comment by ecnivtwelve** [comment]
> je met pas celle qui ont des pr associées et je garde celle que je pense intéressantes essaye de regarder ca: #40 #46 #48 #151 ? #153 #159 #291 #300 #319 #321 #334 #353 #381 #383 #386 #398

ce n'est pas parce qu'elles sont anciennes qu'elles sont peu pertinentes -> elles servent de rappel et de discussion sur ces fonctionnalités secondaires ou complèxes
