### ISSUE TITLE
[Feature]: support carte jeune région Occitanie

### ISSUE THREAD

**Issue by OmegaStator** [PapillonApp/papillon-v7#503]
### Description de la fonctionnalité

- Ajout de fonctionalités liées à la carte jeune région occitanie (voir les offres disponibles, combien nous reste t-il)
- possibilité de passer sa carte au self ou n'importe où via l'app (intégration google pay ?)

**Comment by raphckrman** [comment]
Salut, il y a déjà eu ce type de suggestions, sauf que la plupart des cartes NFC de cantine (même pas spécifiquement eux) sont protégé par des types de NFC spécifique

**Comment by raphckrman** [comment]
Après pour les Self il y a déjà une fonctionnalité intégrant les QRCodes si tu as ça

**Comment by oxrsh** [comment]
Je suis presque sûr que l'argent sur les cartes Occitanie est enregistré dans l'établissement et pas sur ta carte, donc pour moi impossible, et puis oui elles sont sécurisées
