### ISSUE TITLE
[Enhancement] Meilleure interface devoirs

### ISSUE THREAD

**Issue by Nicolasfr340** [PapillonApp/papillon-v7#515]
### Description du problème

Actuellement ce n’est pas forcément très agréable de lire les devoirs ;
![IMG_0268](https://github.com/user-attachments/assets/a0589cf6-b5cf-44c7-a058-6e3d93a46062)
![IMG_0269](https://github.com/user-attachments/assets/21caa18e-1cb1-45c9-883a-7cde0e69d3bd)
- Les espaces inter-lignes sont énormes : on a l’impression de se noyer dans les devoirs tellement ils prennent de la place

![IMG_1228](https://github.com/user-attachments/assets/95cb1c0f-e49a-456b-8092-8a4dec74bc9e)
- Les traits séparants les matières ne sont pas assez prononcés, on se perd dans les matières des devoirs

### Description de l'amélioration

- Épaissir les traits entre les matières dans les devoirs (accentuer la séparation entre les matières des devoirs)
- Réduire l’espace entre les lignes

### Contexte supplémentaire

C’est du détail certes, mais certains du Discord sont du même avis
Et peut-être rajouter des options pour modifier la mise en page des devoirs, ça rajouterait de la personnalisation à l’app

**Comment by Kgeek33** [comment]
Wtfff 🤣🤣😭😭😭
Alors là (_c'est moi qui ai intégré cette amélioration d'affichage_), je m'attendais pas à voir un si beau rendu 🤣🤣

Plus sérieusement, je vais voir ce qui pose problème, ça doit être sûrement la police d'écriture

**Comment by raphckrman** [comment]
sur Pronote j'ai pas ça personnellement

**Comment by Kgeek33** [comment]
Oui, moi non plus !
Si peut être de temps en temps où les devoirs commencent et se terminent avec un retour à la ligne

**Comment by Nicolasfr340** [comment]
> Wtfff 🤣🤣😭😭😭
> Alors là (_c'est moi qui ai intégré cette amélioration d'affichage_), je m'attendais pas à voir un si beau rendu 🤣🤣
> 
> Plus sérieusement, je vais voir ce qui pose problème, ça doit être sûrement la police d'écriture 

ah 😂

j'ai qlq autres trucs à dire concernant ton interface

- les semaines fonctionnent comment? ![image](https://github.com/user-attachments/assets/6de56827-eb6f-4ff6-b359-c1607d2d320c) ce serait mieux d'afficher le numéro de la semaine selon le nouvel an plutôt (1 janvier = semaine 1), et puis quand on clique sur le bouton semaine ce serait intéressant d'avoir une mini interface avec le nombre de semaine depuis la rentrée, qlq dates (En gros une grosse vue calendrier avec d'indiquer les jours d'école, les jours de vacances, les jours fériés, les jours d'épreuves etc (et pourquoi pas avec possibilité de rajouter nos propres events)

- rajouter des infos sur les devoirs par le biais d'un bouton déroulant ![image](https://github.com/user-attachments/assets/b05f50bf-4e7d-4993-a206-6cbc03909e9f) du style le prof, l'heure du cours, date de quand le devoir a été donné lien vers contenu de séance des cours précédents et l'actuel (car des fois les profs postent pour le jour)

**Comment by Kgeek33** [comment]
> les semaines fonctionnent comment?

Semaine 1 = Semaine de la rentrée (donc semaine du 4 septembre)

> ce serait mieux d'afficher le numéro de la semaine selon le nouvel an plutôt (1 janvier = semaine 1), et puis quand on clique sur le bouton semaine ce serait intéressant d'avoir une mini interface avec le nombre de semaine depuis la rentrée, qlq dates (En gros une grosse vue calendrier avec d'indiquer les jours d'école, les jours de vacances, les jours fériés, les jours d'épreuves etc (et pourquoi pas avec possibilité de rajouter nos propres events)

A voir avec les autres sur la proposition de Semaine 1 = 1er janvier
pour ton autre proposition, cela semble difficile à être intégré (car déjà que quand on clique dessus, c'est extrêmement lent, alors ajouter ça ferait empirer la chose, selon moi bien sûr). 

> du style le prof, l'heure du cours, date de quand le devoir a été donné lien vers contenu de séance des cours précédents et l'actuel (car des fois les profs postent pour le jour)

à voir si pawnote le fait, surement que oui, merci des propositions en tout cas !

**Comment by Nicolasfr340** [comment]
Content de pouvoir aider au développement de l'app !
