### ISSUE TITLE
non possibilité de se déplacer sur les jours rapidement 

### ISSUE THREAD

**Issue by Louis454545** [PapillonApp/papillon-v7#52]
### Description du problème

Si je veux me balader sur plusieurs ca vas être très long.

### Description de l'amélioration

J'aimerais pourvoir glisser mon doigt comme dans la vidéo pour me déplacer a travers les jours

### Contexte supplémentaire

https://github.com/user-attachments/assets/f7553afe-37f4-43a0-8e66-07683aa97d2e

**Comment by tryon-dev** [comment]
Bonsoir, Non.

**Comment by Rexxt** [comment]
où est le professionalisme ?

**Comment by godetremy** [comment]
@tryon-dev PTDRRRRRRR

Non plus sérieusement ont pourrais intégrer un calendrier non ? ça serrais plus simple !

**Comment by Rexxt** [comment]
+1

**Comment by tryon-dev** [comment]
y'a deja un calendrier

**Comment by tryon-dev** [comment]
![image](https://github.com/user-attachments/assets/a1776737-0268-4fbf-bd0e-cb40f135a651)

**Comment by godetremy** [comment]
@tryon-dev My bad !

**Comment by Louis454545** [comment]
> où est le professionalisme ?

Ah désolé, j'ai pas trop eu le temps de rédiger. Deso si as ressenti ça

**Comment by tryon-dev** [comment]
c'est pour moi qu'il parle je pense

**Comment by Rexxt** [comment]
elle déjà, mais oui

**Comment by tryon-dev** [comment]
mybad

**Comment by Rexxt** [comment]
mon mauvais, on parle français ici; tu peux close l'issue je pense

**Comment by tryon-dev** [comment]
okay
