### ISSUE TITLE
[Feature]: Export en iCal son EDT

### ISSUE THREAD

**Issue by RaphTHLN** [PapillonApp/papillon-v7#520]
### Description de la fonctionnalité

Hello! J'aimerais bien si possible qu'on puisse export en iCal son emploi du temps vu que l'ajout n'y est pas sur Pronote. 
Vu que je suis probablement pas le seul a fonctionner sur Google Calendar (dumoins je crois), je pense que cela pourrait être super utile :)

Bonne journée !

**Comment by Skythrew** [comment]
Hello ! C'est déjà en cours de discussion dans #431 principalement :+1:
