### ISSUE TITLE
Parent interface 

### ISSUE THREAD

**Issue by Awakno** [PapillonApp/papillon-v7#531]
### Description de la fonctionnalité

Ajouter l’interface parent à papillon afin de permettre à tout la famille d’être sur papillon

**Comment by codeuriii** [comment]
est ce que tu as regardé si tu faisait pas un doublon ?

**Comment by Awakno** [comment]
J'ai vérifié mais il me semble que je n'ai pas trouvé issue en rapport avec ça

**Comment by skyfr0676** [comment]
je vais check si ya pas déjà eu un pr sur ça, et je vais **essayer** (j'insiste sur le mot, je commence tous juste a comprendre le typescript) d'implémenter ça

**Comment by Skythrew** [comment]
Le problème est que le wrapper de l'API Pronote que nous utilisons, à savoir [Pawnote](https://github.com/LiterateInk/Pawnote), ne supporte pas encore le compte parent, comme cela a été dit dans l'issue #155 . Ce n'est pour l'instant pas la priorité, bien qu'on pense sérieusement à l'implémenter du côté de chez Pawnote :+1:

**Comment by codeuriii** [comment]
tiens tiens, on dirait bien que tu n'as pas cherché dans les issues...

**Comment by yannouuuu** [comment]
https://github.com/PapillonApp/Papillon/issues/176
