### ISSUE TITLE
[Enhancement]: avoir les compétences 

### ISSUE THREAD

**Issue by sicada30** [PapillonApp/papillon-v7#541]
### Description du problème

Mon collège utilise des compétences (notés de 1 à 6) et je n'y ait pas accès dans l'app. J'ai seulement les notes qui s'affichent vides. 

### Description de l'amélioration

Serait t'il possible d'avoir accès aux compétences ?

**Comment by raphckrman** [comment]
Salut, cette fonctionnalité sera disponible à la prochaine mise à jour elle a déjà était réalisé.

**Comment by Clmnnt** [comment]
possible de close l’issue ?
