### ISSUE TITLE
[Enhancement]: Bloquer la connexion via la démo d'Index Éducation

### ISSUE THREAD

**Issue by oriionn** [PapillonApp/papillon-v7#57]
### Description du problème

Beaucoup de gens utilisent l'instance de démo de PRONOTE pour tester Papillon. Cependant, Pawnote ne supporte pas cette instance.

### Description de l'amélioration

Lorsque quelqu'un tente de se connecter via cette instance, afficher une alerte lui disant que l'instance n'est pas compatible et ne pas le laisser se connecter.

On pourrait même penser à préparer une démo de Papillon directement dans l'application pour pousser l'idée plus loin.

### Contexte supplémentaire

Pour éviter des issues tel que #54.

**Comment by vexcited** [comment]
J'aimerais rajouter que c'est ce que fait l'application mobile PRONOTE officielle.

**Comment by Gabriel29306** [comment]
Il y a juste une propriété à regarder donc c'est facilement faisable

**Comment by vexcited** [comment]
Même pas, tu regardes si l'URL contient `demo.index-education.net`

**Comment by Gabriel29306** [comment]
Il peux y avoir d'autres instances démo

**Comment by TinAD17tin** [comment]
RIP, le compte demo permettait au moins de voir à quoi ressemble papillon avant d’avoir un compte PRONOTE valide.
(J’pense faudrait rajouter notre faux compte demo qui permettrait de juste voir a quoi ressemble l’app)

**Comment by TinAD17tin** [comment]
Genre en mode « se connecte sans services », ou tous serait faux mais permettrait de tester les trcu basique et de voir ce qu’il se passe (notamment les textes qui étaient pas dans la bonne couleur)

**Comment by ecnivtwelve** [comment]
On pourrait le laisser se connecter, a condition qu'il voit le disclaimer pendant un temps minimum (genre 10 secondes) et qu'il coche un truc "oui j'ai compris"

**Comment by TinAD17tin** [comment]
As you want

**Comment by oriionn** [comment]
> Genre en mode « se connecte sans services », ou tous serait faux mais permettrait de tester les trcu basique et de voir ce qu’il se passe (notamment les textes qui étaient pas dans la bonne couleur)

Un peu ce que j'ai précisé à la fin de la description de l'amélioration du coup, ajouter notre propre démo pour pousser l'idée plus loin

**Comment by Orafilynie** [comment]
> Il peux y avoir d'autres instances démo

Comme la dis Vexcited dans sa doc Pawnote, on a juste a lire la valeur de IsDemo

« You can know if a server is a demonstration or not by reading the isDemo property on a Pronote instance in Pawnote. »

**Comment by oriionn** [comment]
> On pourrait le laisser se connecter, a condition qu'il voit le disclaimer pendant un temps minimum (genre 10 secondes) et qu'il coche un truc "oui j'ai compris"

J'y ai pensé, mais je suis sûr qu'il y a des gens qui seraient encore capables de dire "POURQUOI ÇA NE MARCHE PAS ?".

**Comment by vexcited** [comment]
> > Il peux y avoir d'autres instances démo
> 
> Comme la dis Vexcited dans sa doc Pawnote, on a juste a lire la valeur de IsDemo
> 
> « You can know if a server is a demonstration or not by reading the isDemo property on a Pronote instance in Pawnote. »

J'ai pas mis à jour cette partie de ma documentation...

**Comment by tom-theret** [comment]
Au pire Papillon pourrait nous mettre une VM commune à disposition ! Un w10 iot lstc qui consomme rien avec PRONOTE puis ça va !
