### ISSUE TITLE
[Enhancement]: Intégration de Sourcery AI pour améliorer les revues de code

### ISSUE THREAD

**Issue by Louis454545** [PapillonApp/papillon-v7#79]
### Description du problème

Nos revues de code actuelles peuvent être lentes et ne détectent pas toujours tous les problèmes potentiels. Nous avons besoin d'un outil pour accélérer et améliorer ce processus.

### Description de l'amélioration

Intégrer Sourcery AI (https://sourcery.ai/) à notre workflow GitHub pour automatiser et améliorer nos revues de code. Sourcery AI est un outil d'IA qui agit comme un réviseur de code supplémentaire, offrant des commentaires instantanés sur chaque pull request.

Avantages principaux :
1. Revues de code plus rapides et toujours disponibles
2. Détection automatique des bugs et des risques de sécurité
3. Vérification de la complexité du code pour maintenir une bonne conception
4. Commentaires en ligne et suggestions pertinentes

Cette intégration permettra d'optimiser notre processus de développement en fournissant une analyse automatique et des suggestions d'amélioration pour chaque pull request.

### Contexte supplémentaire

Sourcery AI s'intègre directement à GitHub et fonctionne comme un réviseur de code supplémentaire dans notre équipe. Il utilise l'IA pour analyser le code et fournir des commentaires utiles, permettant à nos développeurs de se concentrer sur des tâches plus complexes.

**Comment by Louis454545** [comment]
https://github.com/apps/sourcery-ai

**Comment by Rexxt** [comment]
pas d'IA par chez nous ❌

**Comment by Gabriel29306** [comment]
Le mec qui est matrixé dès que ça parle d'ia

**Comment by Louis454545** [comment]
Non c'est incroyable le truc

**Comment by Louis454545** [comment]
ca donne ca
![image](https://github.com/user-attachments/assets/24d11831-cea2-431d-9629-509a77dd66b3)

**Comment by Orafilynie** [comment]
Ça à l'air pas mal il faudrait essayer sur 1 ou 2 pull request pour tester

**Comment by oriionn** [comment]
Pour citer Mizu, "Pas d'IA par chez nous"

**Comment by Rexxt** [comment]
merci orion

**Comment by Louis454545** [comment]
![image](https://github.com/user-attachments/assets/7f24694b-4b75-40c3-b363-139aebb93257)

**Comment by Louis454545** [comment]
> Pour citer Mizu, "Pas d'IA par chez nous"

ca peut quand meme aider

**Comment by oriionn** [comment]
> > Pour citer Mizu, "Pas d'IA par chez nous"
> 
> ca peut quand meme aider

![image](https://github.com/user-attachments/assets/6217d70a-d4eb-4718-b5f1-4ebc3521d656)
🤓

**Comment by Louis454545** [comment]
> > > Pour citer Mizu, "Pas d'IA par chez nous"
> > 
> > ca peut quand meme aider
> 
> ![image](https://github.com/user-attachments/assets/6217d70a-d4eb-4718-b5f1-4ebc3521d656)
> 🤓 

C'est une issue et non pas une pr 🤓

**Comment by oriionn** [comment]
> > > > Pour citer Mizu, "Pas d'IA par chez nous"
> > > 
> > > 
> > > ca peut quand meme aider
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/38093786/362254811-6217d70a-d4eb-4718-b5f1-4ebc3521d656.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDQ4OTIsIm5iZiI6MTcyNDg0NDU5MiwicGF0aCI6Ii8zODA5Mzc4Ni8zNjIyNTQ4MTEtNjIxN2Q3MGEtZDRlYi00NzE4LWI1ZjEtNGViYzM1MjFkNjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDExMjk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZjg0YzVkODA4NTU0MTVlMGFjNDIyNDQyNTVmZjBkNzE5NzM5MTg4MDQ2ZmVmNmRhY2FjN2MzZTdlOGY4YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yKV2H6sgaSRMAEFMoR7xlOYoxCM8rFVlIqRDpn5IMRA)
> > 🤓
> 
> C'est une issue et non pas une pr 🤓

Sauf que si tu réfléchis un minimum, faudra une PR pour compléter ton issue...

**Comment by oriionn** [comment]
Dites non à l'IA !

**Comment by tryon-dev** [comment]
Pas besoin d'IA

**Comment by Louis454545** [comment]
> > > > > Pour citer Mizu, "Pas d'IA par chez nous"
> > > > 
> > > > 
> > > > ca peut quand meme aider
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/38093786/362254811-6217d70a-d4eb-4718-b5f1-4ebc3521d656.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDQ4OTIsIm5iZiI6MTcyNDg0NDU5MiwicGF0aCI6Ii8zODA5Mzc4Ni8zNjIyNTQ4MTEtNjIxN2Q3MGEtZDRlYi00NzE4LWI1ZjEtNGViYzM1MjFkNjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDExMjk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZjg0YzVkODA4NTU0MTVlMGFjNDIyNDQyNTVmZjBkNzE5NzM5MTg4MDQ2ZmVmNmRhY2FjN2MzZTdlOGY4YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yKV2H6sgaSRMAEFMoR7xlOYoxCM8rFVlIqRDpn5IMRA)
> > > 🤓
> > 
> > 
> > C'est une issue et non pas une pr 🤓
> 
> Sauf que si tu réfléchis un minimum, faudra une PR pour compléter ton issue...

reflechie un tout petit peu, c'est une app github et pas un actions 🤓

**Comment by Louis454545** [comment]
> Dites non à l'IA !



> Pas besoin d'IA

c'est pas pour faire une vrai review, juste pour une pre review

**Comment by TinAD17tin** [comment]
Non a l’IA !
(J’ai pas d’arguments mais Asy)

**Comment by oriionn** [comment]
> > Dites non à l'IA !
> 
> > Pas besoin d'IA
> 
> c'est pas pour faire une vrai review, juste pour une pre review

On s'enfous, pas d'IA, merci

**Comment by oriionn** [comment]
> > > > > > Pour citer Mizu, "Pas d'IA par chez nous"
> > > > > 
> > > > > 
> > > > > ca peut quand meme aider
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/38093786/362254811-6217d70a-d4eb-4718-b5f1-4ebc3521d656.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDQ4OTIsIm5iZiI6MTcyNDg0NDU5MiwicGF0aCI6Ii8zODA5Mzc4Ni8zNjIyNTQ4MTEtNjIxN2Q3MGEtZDRlYi00NzE4LWI1ZjEtNGViYzM1MjFkNjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDExMjk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZjg0YzVkODA4NTU0MTVlMGFjNDIyNDQyNTVmZjBkNzE5NzM5MTg4MDQ2ZmVmNmRhY2FjN2MzZTdlOGY4YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yKV2H6sgaSRMAEFMoR7xlOYoxCM8rFVlIqRDpn5IMRA)
> > > > 🤓
> > > 
> > > 
> > > C'est une issue et non pas une pr 🤓
> > 
> > 
> > Sauf que si tu réfléchis un minimum, faudra une PR pour compléter ton issue...
> 
> reflechie un tout petit peu, c'est une app github et pas un actions 🤓

Bref ne casse pas les couilles, tu as très bien compris ce que Vince voulait dire
