### ISSUE TITLE
[Feature]: Marquer une actualité comme lue

### ISSUE THREAD

**Issue by vexcited** [PapillonApp/papillon-v7#9]
### Description de la fonctionnalité

Dans les actualités il faudrait qu'on puisse marquer une actualité comme lue ou non lue.

Il faudrait aussi que si l'actualité est non lue et qu'on accède à ses informations (= clique dessus) l'actualité devient lue.

### Contexte supplémentaire

Pawnote implémente cette fonctionnalité.

**Comment by Rexxt** [comment]
j'imagine que ça prendra pas trop longtemps à faire

**Comment by Kgeek33** [comment]
L'issue peut être closed : #210
