### ISSUE TITLE
ajout la possibilité d'utiliser les couleurs Monet sur Android 

### ISSUE THREAD

**Issue by Louis454545** [PapillonApp/papillon-v7#95]
### Description du problème

Je n'ai pas la possibilité d'utiliser les couleurs monet

### Description de l'amélioration

Pouvoir utiliser les couleurs monet

**Comment by Rexxt** [comment]
le moteur de material you ?

**Comment by Gabriel29306** [comment]
Monet est bien le moteur de Material You.
Sauf erreur de ma part, c'est un choix volontaire de ne pas l'inclure dans l'application.

**Comment by LeGeek01** [comment]
pourquoi ça ?

**Comment by Gabriel29306** [comment]
@toi-et-moi

**Comment by Rexxt** [comment]
> pourquoi ça ?

papillon fait des choix stylistiques qui lui sont propres

**Comment by yannouuuu** [comment]
je considère que l'issue est close
